#
# Autogenerated by Thrift Compiler (0.22.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py
#

from thrift.Thrift import TType, TMessageType, TFrozenDict, TException, TApplicationException
from thrift.protocol.TProtocol import TProtocolException
from thrift.TRecursive import fix_spec
from uuid import UUID

import sys
import logging
from .ttypes import *
from thrift.Thrift import TProcessor
from thrift.transport import TTransport
all_structs = []


class Iface(object):
    def getRoleList(self, normal, page, page_size):
        """
        @description 获取游戏帮会设置的角色权限列表
        @param normal API请求基础信息
        @param page 页码，从1开始
        @param page_size 每页大小，从1开始
        @returns RoleList 角色列表信息
          - time: string 时间戳
          - role_list: list[Role] 角色列表
            - id: i32 角色ID
            - name: string 角色名称
            - permissions: string 权限字符串（用|分隔）
            - create_time: i32 创建时间戳
            - description: string 角色描述（可选）
        @throws NormalException 获取角色列表时可能抛出的异常

        Parameters:
         - normal
         - page
         - page_size

        """
        pass


class Client(Iface):
    def __init__(self, iprot, oprot=None):
        self._iprot = self._oprot = iprot
        if oprot is not None:
            self._oprot = oprot
        self._seqid = 0

    def getRoleList(self, normal, page, page_size):
        """
        @description 获取游戏帮会设置的角色权限列表
        @param normal API请求基础信息
        @param page 页码，从1开始
        @param page_size 每页大小，从1开始
        @returns RoleList 角色列表信息
          - time: string 时间戳
          - role_list: list[Role] 角色列表
            - id: i32 角色ID
            - name: string 角色名称
            - permissions: string 权限字符串（用|分隔）
            - create_time: i32 创建时间戳
            - description: string 角色描述（可选）
        @throws NormalException 获取角色列表时可能抛出的异常

        Parameters:
         - normal
         - page
         - page_size

        """
        self.send_getRoleList(normal, page, page_size)
        return self.recv_getRoleList()

    def send_getRoleList(self, normal, page, page_size):
        self._oprot.writeMessageBegin('getRoleList', TMessageType.CALL, self._seqid)
        args = getRoleList_args()
        args.normal = normal
        args.page = page
        args.page_size = page_size
        args.write(self._oprot)
        self._oprot.writeMessageEnd()
        self._oprot.trans.flush()

    def recv_getRoleList(self):
        iprot = self._iprot
        (fname, mtype, rseqid) = iprot.readMessageBegin()
        if mtype == TMessageType.EXCEPTION:
            x = TApplicationException()
            x.read(iprot)
            iprot.readMessageEnd()
            raise x
        result = getRoleList_result()
        result.read(iprot)
        iprot.readMessageEnd()
        if result.success is not None:
            return result.success
        if result.normalException is not None:
            raise result.normalException
        raise TApplicationException(TApplicationException.MISSING_RESULT, "getRoleList failed: unknown result")


class Processor(Iface, TProcessor):
    def __init__(self, handler):
        self._handler = handler
        self._processMap = {}
        self._processMap["getRoleList"] = Processor.process_getRoleList
        self._on_message_begin = None

    def on_message_begin(self, func):
        self._on_message_begin = func

    def process(self, iprot, oprot):
        (name, type, seqid) = iprot.readMessageBegin()
        if self._on_message_begin:
            self._on_message_begin(name, type, seqid)
        if name not in self._processMap:
            iprot.skip(TType.STRUCT)
            iprot.readMessageEnd()
            x = TApplicationException(TApplicationException.UNKNOWN_METHOD, 'Unknown function %s' % (name))
            oprot.writeMessageBegin(name, TMessageType.EXCEPTION, seqid)
            x.write(oprot)
            oprot.writeMessageEnd()
            oprot.trans.flush()
            return
        else:
            self._processMap[name](self, seqid, iprot, oprot)
        return True

    def process_getRoleList(self, seqid, iprot, oprot):
        args = getRoleList_args()
        args.read(iprot)
        iprot.readMessageEnd()
        result = getRoleList_result()
        try:
            result.success = self._handler.getRoleList(args.normal, args.page, args.page_size)
            msg_type = TMessageType.REPLY
        except TTransport.TTransportException:
            raise
        except shared.ttypes.NormalException as normalException:
            msg_type = TMessageType.REPLY
            result.normalException = normalException
        except TApplicationException as ex:
            logging.exception('TApplication exception in handler')
            msg_type = TMessageType.EXCEPTION
            result = ex
        except Exception:
            logging.exception('Unexpected exception in handler')
            msg_type = TMessageType.EXCEPTION
            result = TApplicationException(TApplicationException.INTERNAL_ERROR, 'Internal error')
        oprot.writeMessageBegin("getRoleList", msg_type, seqid)
        result.write(oprot)
        oprot.writeMessageEnd()
        oprot.trans.flush()

# HELPER FUNCTIONS AND STRUCTURES


class getRoleList_args(object):
    """
    Attributes:
     - normal
     - page
     - page_size

    """
    thrift_spec = None


    def __init__(self, normal = None, page = None, page_size = None,):
        self.normal = normal
        self.page = page
        self.page_size = page_size

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.STRUCT:
                    self.normal = shared.ttypes.Normal()
                    self.normal.read(iprot)
                else:
                    iprot.skip(ftype)
            elif fid == 2:
                if ftype == TType.I32:
                    self.page = iprot.readI32()
                else:
                    iprot.skip(ftype)
            elif fid == 3:
                if ftype == TType.I32:
                    self.page_size = iprot.readI32()
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        self.validate()
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('getRoleList_args')
        if self.normal is not None:
            oprot.writeFieldBegin('normal', TType.STRUCT, 1)
            self.normal.write(oprot)
            oprot.writeFieldEnd()
        if self.page is not None:
            oprot.writeFieldBegin('page', TType.I32, 2)
            oprot.writeI32(self.page)
            oprot.writeFieldEnd()
        if self.page_size is not None:
            oprot.writeFieldBegin('page_size', TType.I32, 3)
            oprot.writeI32(self.page_size)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)
all_structs.append(getRoleList_args)
getRoleList_args.thrift_spec = (
    None,  # 0
    (1, TType.STRUCT, 'normal', [shared.ttypes.Normal, None], None, ),  # 1
    (2, TType.I32, 'page', None, None, ),  # 2
    (3, TType.I32, 'page_size', None, None, ),  # 3
)


class getRoleList_result(object):
    """
    Attributes:
     - success
     - normalException

    """
    thrift_spec = None


    def __init__(self, success = None, normalException = None,):
        self.success = success
        self.normalException = normalException

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 0:
                if ftype == TType.STRUCT:
                    self.success = RoleList()
                    self.success.read(iprot)
                else:
                    iprot.skip(ftype)
            elif fid == 1:
                if ftype == TType.STRUCT:
                    self.normalException = shared.ttypes.NormalException.read(iprot)
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        self.validate()
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('getRoleList_result')
        if self.success is not None:
            oprot.writeFieldBegin('success', TType.STRUCT, 0)
            self.success.write(oprot)
            oprot.writeFieldEnd()
        if self.normalException is not None:
            oprot.writeFieldBegin('normalException', TType.STRUCT, 1)
            self.normalException.write(oprot)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)
all_structs.append(getRoleList_result)
getRoleList_result.thrift_spec = (
    (0, TType.STRUCT, 'success', [RoleList, None], None, ),  # 0
    (1, TType.STRUCT, 'normalException', [shared.ttypes.NormalException, None], None, ),  # 1
)
fix_spec(all_structs)
del all_structs
