#
# Autogenerated by Thrift Compiler (0.22.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py
#

from thrift.Thrift import TType, TMessageType, TFrozenDict, TException, TApplicationException
from thrift.protocol.TProtocol import TProtocolException
from thrift.TRecursive import fix_spec
from uuid import UUID

import sys
import logging
from .ttypes import *
from thrift.Thrift import TProcessor
from thrift.transport import TTransport
all_structs = []


class Iface(object):
    def unionMembers(self, normal, union_id):
        """
        @description 获取指定军队的所有成员信息
        @param normal API请求基础信息
        @param union_id 军队id
        @returns UnionMembers 军队成员信息
          - time: string 时间戳
          - members: list<Member> 成员列表
        @throws NormalException 获取成员列表时可能抛出的异常

        Parameters:
         - normal
         - union_id

        """
        pass

    def unionInfo(self, normal, union_id):
        """
        @description 获取指定军队的详细信息
        @param normal API请求基础信息
        @param union_id 军队id
        @returns UnionInfo 军队详细信息
          - time: string 时间戳
          - union: Union 军队信息
        @note 需要该用户账号存档，加入军队
        @throws NormalException 获取军队信息时可能抛出的异常

        Parameters:
         - normal
         - union_id

        """
        pass

    def setMemberExtra(self, normal, type, extra, union_id, uid, index):
        """
        @description 修改指定用户的扩展信息
        @param normal API请求基础信息
        @param type 操作类型 (1: 修改自己的扩展信息, 非1: 修改指定用户的扩展信息)
        @param extra 扩展信息 (AMF3格式)
        @param union_id 帮会id (当type不为1时必填, 为1时填0)
        @param uid 用户id (当type不为1时必填, 为1时填0)
        @param index 用户存档索引 (当type不为1时必填, 为1时填0)
        @throws NormalException 设置成员扩展信息时可能抛出的异常

        Parameters:
         - normal
         - type
         - extra
         - union_id
         - uid
         - index

        """
        pass

    def setUnionExtra(self, normal, type, extra, union_id):
        """
        @description 修改帮会的扩展信息
        @param normal API请求基础信息
        @param type 操作类型 (1: 帮主修改帮会扩展信息, 非1: 成员修改帮会扩展信息)
        @param extra 扩展信息
        @param union_id 变更当前帮会 (unionId可以为0)
        @throws NormalException 设置军队扩展信息时可能抛出的异常

        Parameters:
         - normal
         - type
         - extra
         - union_id

        """
        pass

    def deleteContributionPersonal(self, normal, contribution):
        """
        @description 消耗指定数量的个人贡献值
        @param normal API请求基础信息
        @param contribution 消耗的贡献值
        @throws NormalException 消耗贡献值时可能抛出的异常

        Parameters:
         - normal
         - contribution

        """
        pass

    def setRole(self, normal, uid, index, role_id):
        """
        @description 为指定用户设置角色权限
        @param normal API请求基础信息
        @param uid 被设置的用户的ID编号
        @param index 被设置的用户的存档索引 (范围0-7)
        @param role_id 被设置成为的角色权限编号 (如果role_id为0，则是取消角色)
        @throws NormalException 设置成员角色时可能抛出的异常

        Parameters:
         - normal
         - uid
         - index
         - role_id

        """
        pass

    def unionLog(self, normal, page_num, page_size):
        """
        @description 获取军队的操作日志信息
        @param normal API请求基础信息
        @param page_num 第几页
        @param page_size 每页条数
        @returns LogInfo 日志信息


          - time: string 时间戳
          - log_list: list[string] 日志列表 (需要将字符串转字典)
        @throws NormalException 获取日志时可能抛出的异常

        Parameters:
         - normal
         - page_num
         - page_size

        """
        pass

    def unionQuit(self, normal):
        """
        @description 当前用户退出所在的军队
        @param normal API请求基础信息
        @throws NormalException 退出军队时可能抛出的异常

        Parameters:
         - normal

        """
        pass


class Client(Iface):
    def __init__(self, iprot, oprot=None):
        self._iprot = self._oprot = iprot
        if oprot is not None:
            self._oprot = oprot
        self._seqid = 0

    def unionMembers(self, normal, union_id):
        """
        @description 获取指定军队的所有成员信息
        @param normal API请求基础信息
        @param union_id 军队id
        @returns UnionMembers 军队成员信息
          - time: string 时间戳
          - members: list<Member> 成员列表
        @throws NormalException 获取成员列表时可能抛出的异常

        Parameters:
         - normal
         - union_id

        """
        self.send_unionMembers(normal, union_id)
        return self.recv_unionMembers()

    def send_unionMembers(self, normal, union_id):
        self._oprot.writeMessageBegin('unionMembers', TMessageType.CALL, self._seqid)
        args = unionMembers_args()
        args.normal = normal
        args.union_id = union_id
        args.write(self._oprot)
        self._oprot.writeMessageEnd()
        self._oprot.trans.flush()

    def recv_unionMembers(self):
        iprot = self._iprot
        (fname, mtype, rseqid) = iprot.readMessageBegin()
        if mtype == TMessageType.EXCEPTION:
            x = TApplicationException()
            x.read(iprot)
            iprot.readMessageEnd()
            raise x
        result = unionMembers_result()
        result.read(iprot)
        iprot.readMessageEnd()
        if result.success is not None:
            return result.success
        if result.normalException is not None:
            raise result.normalException
        raise TApplicationException(TApplicationException.MISSING_RESULT, "unionMembers failed: unknown result")

    def unionInfo(self, normal, union_id):
        """
        @description 获取指定军队的详细信息
        @param normal API请求基础信息
        @param union_id 军队id
        @returns UnionInfo 军队详细信息
          - time: string 时间戳
          - union: Union 军队信息
        @note 需要该用户账号存档，加入军队
        @throws NormalException 获取军队信息时可能抛出的异常

        Parameters:
         - normal
         - union_id

        """
        self.send_unionInfo(normal, union_id)
        return self.recv_unionInfo()

    def send_unionInfo(self, normal, union_id):
        self._oprot.writeMessageBegin('unionInfo', TMessageType.CALL, self._seqid)
        args = unionInfo_args()
        args.normal = normal
        args.union_id = union_id
        args.write(self._oprot)
        self._oprot.writeMessageEnd()
        self._oprot.trans.flush()

    def recv_unionInfo(self):
        iprot = self._iprot
        (fname, mtype, rseqid) = iprot.readMessageBegin()
        if mtype == TMessageType.EXCEPTION:
            x = TApplicationException()
            x.read(iprot)
            iprot.readMessageEnd()
            raise x
        result = unionInfo_result()
        result.read(iprot)
        iprot.readMessageEnd()
        if result.success is not None:
            return result.success
        if result.normalException is not None:
            raise result.normalException
        raise TApplicationException(TApplicationException.MISSING_RESULT, "unionInfo failed: unknown result")

    def setMemberExtra(self, normal, type, extra, union_id, uid, index):
        """
        @description 修改指定用户的扩展信息
        @param normal API请求基础信息
        @param type 操作类型 (1: 修改自己的扩展信息, 非1: 修改指定用户的扩展信息)
        @param extra 扩展信息 (AMF3格式)
        @param union_id 帮会id (当type不为1时必填, 为1时填0)
        @param uid 用户id (当type不为1时必填, 为1时填0)
        @param index 用户存档索引 (当type不为1时必填, 为1时填0)
        @throws NormalException 设置成员扩展信息时可能抛出的异常

        Parameters:
         - normal
         - type
         - extra
         - union_id
         - uid
         - index

        """
        self.send_setMemberExtra(normal, type, extra, union_id, uid, index)
        self.recv_setMemberExtra()

    def send_setMemberExtra(self, normal, type, extra, union_id, uid, index):
        self._oprot.writeMessageBegin('setMemberExtra', TMessageType.CALL, self._seqid)
        args = setMemberExtra_args()
        args.normal = normal
        args.type = type
        args.extra = extra
        args.union_id = union_id
        args.uid = uid
        args.index = index
        args.write(self._oprot)
        self._oprot.writeMessageEnd()
        self._oprot.trans.flush()

    def recv_setMemberExtra(self):
        iprot = self._iprot
        (fname, mtype, rseqid) = iprot.readMessageBegin()
        if mtype == TMessageType.EXCEPTION:
            x = TApplicationException()
            x.read(iprot)
            iprot.readMessageEnd()
            raise x
        result = setMemberExtra_result()
        result.read(iprot)
        iprot.readMessageEnd()
        if result.normalException is not None:
            raise result.normalException
        return

    def setUnionExtra(self, normal, type, extra, union_id):
        """
        @description 修改帮会的扩展信息
        @param normal API请求基础信息
        @param type 操作类型 (1: 帮主修改帮会扩展信息, 非1: 成员修改帮会扩展信息)
        @param extra 扩展信息
        @param union_id 变更当前帮会 (unionId可以为0)
        @throws NormalException 设置军队扩展信息时可能抛出的异常

        Parameters:
         - normal
         - type
         - extra
         - union_id

        """
        self.send_setUnionExtra(normal, type, extra, union_id)
        self.recv_setUnionExtra()

    def send_setUnionExtra(self, normal, type, extra, union_id):
        self._oprot.writeMessageBegin('setUnionExtra', TMessageType.CALL, self._seqid)
        args = setUnionExtra_args()
        args.normal = normal
        args.type = type
        args.extra = extra
        args.union_id = union_id
        args.write(self._oprot)
        self._oprot.writeMessageEnd()
        self._oprot.trans.flush()

    def recv_setUnionExtra(self):
        iprot = self._iprot
        (fname, mtype, rseqid) = iprot.readMessageBegin()
        if mtype == TMessageType.EXCEPTION:
            x = TApplicationException()
            x.read(iprot)
            iprot.readMessageEnd()
            raise x
        result = setUnionExtra_result()
        result.read(iprot)
        iprot.readMessageEnd()
        if result.normalException is not None:
            raise result.normalException
        return

    def deleteContributionPersonal(self, normal, contribution):
        """
        @description 消耗指定数量的个人贡献值
        @param normal API请求基础信息
        @param contribution 消耗的贡献值
        @throws NormalException 消耗贡献值时可能抛出的异常

        Parameters:
         - normal
         - contribution

        """
        self.send_deleteContributionPersonal(normal, contribution)
        self.recv_deleteContributionPersonal()

    def send_deleteContributionPersonal(self, normal, contribution):
        self._oprot.writeMessageBegin('deleteContributionPersonal', TMessageType.CALL, self._seqid)
        args = deleteContributionPersonal_args()
        args.normal = normal
        args.contribution = contribution
        args.write(self._oprot)
        self._oprot.writeMessageEnd()
        self._oprot.trans.flush()

    def recv_deleteContributionPersonal(self):
        iprot = self._iprot
        (fname, mtype, rseqid) = iprot.readMessageBegin()
        if mtype == TMessageType.EXCEPTION:
            x = TApplicationException()
            x.read(iprot)
            iprot.readMessageEnd()
            raise x
        result = deleteContributionPersonal_result()
        result.read(iprot)
        iprot.readMessageEnd()
        if result.normalException is not None:
            raise result.normalException
        return

    def setRole(self, normal, uid, index, role_id):
        """
        @description 为指定用户设置角色权限
        @param normal API请求基础信息
        @param uid 被设置的用户的ID编号
        @param index 被设置的用户的存档索引 (范围0-7)
        @param role_id 被设置成为的角色权限编号 (如果role_id为0，则是取消角色)
        @throws NormalException 设置成员角色时可能抛出的异常

        Parameters:
         - normal
         - uid
         - index
         - role_id

        """
        self.send_setRole(normal, uid, index, role_id)
        self.recv_setRole()

    def send_setRole(self, normal, uid, index, role_id):
        self._oprot.writeMessageBegin('setRole', TMessageType.CALL, self._seqid)
        args = setRole_args()
        args.normal = normal
        args.uid = uid
        args.index = index
        args.role_id = role_id
        args.write(self._oprot)
        self._oprot.writeMessageEnd()
        self._oprot.trans.flush()

    def recv_setRole(self):
        iprot = self._iprot
        (fname, mtype, rseqid) = iprot.readMessageBegin()
        if mtype == TMessageType.EXCEPTION:
            x = TApplicationException()
            x.read(iprot)
            iprot.readMessageEnd()
            raise x
        result = setRole_result()
        result.read(iprot)
        iprot.readMessageEnd()
        if result.normalException is not None:
            raise result.normalException
        return

    def unionLog(self, normal, page_num, page_size):
        """
        @description 获取军队的操作日志信息
        @param normal API请求基础信息
        @param page_num 第几页
        @param page_size 每页条数
        @returns LogInfo 日志信息


          - time: string 时间戳
          - log_list: list[string] 日志列表 (需要将字符串转字典)
        @throws NormalException 获取日志时可能抛出的异常

        Parameters:
         - normal
         - page_num
         - page_size

        """
        self.send_unionLog(normal, page_num, page_size)
        return self.recv_unionLog()

    def send_unionLog(self, normal, page_num, page_size):
        self._oprot.writeMessageBegin('unionLog', TMessageType.CALL, self._seqid)
        args = unionLog_args()
        args.normal = normal
        args.page_num = page_num
        args.page_size = page_size
        args.write(self._oprot)
        self._oprot.writeMessageEnd()
        self._oprot.trans.flush()

    def recv_unionLog(self):
        iprot = self._iprot
        (fname, mtype, rseqid) = iprot.readMessageBegin()
        if mtype == TMessageType.EXCEPTION:
            x = TApplicationException()
            x.read(iprot)
            iprot.readMessageEnd()
            raise x
        result = unionLog_result()
        result.read(iprot)
        iprot.readMessageEnd()
        if result.success is not None:
            return result.success
        if result.normalException is not None:
            raise result.normalException
        raise TApplicationException(TApplicationException.MISSING_RESULT, "unionLog failed: unknown result")

    def unionQuit(self, normal):
        """
        @description 当前用户退出所在的军队
        @param normal API请求基础信息
        @throws NormalException 退出军队时可能抛出的异常

        Parameters:
         - normal

        """
        self.send_unionQuit(normal)
        self.recv_unionQuit()

    def send_unionQuit(self, normal):
        self._oprot.writeMessageBegin('unionQuit', TMessageType.CALL, self._seqid)
        args = unionQuit_args()
        args.normal = normal
        args.write(self._oprot)
        self._oprot.writeMessageEnd()
        self._oprot.trans.flush()

    def recv_unionQuit(self):
        iprot = self._iprot
        (fname, mtype, rseqid) = iprot.readMessageBegin()
        if mtype == TMessageType.EXCEPTION:
            x = TApplicationException()
            x.read(iprot)
            iprot.readMessageEnd()
            raise x
        result = unionQuit_result()
        result.read(iprot)
        iprot.readMessageEnd()
        if result.normalException is not None:
            raise result.normalException
        return


class Processor(Iface, TProcessor):
    def __init__(self, handler):
        self._handler = handler
        self._processMap = {}
        self._processMap["unionMembers"] = Processor.process_unionMembers
        self._processMap["unionInfo"] = Processor.process_unionInfo
        self._processMap["setMemberExtra"] = Processor.process_setMemberExtra
        self._processMap["setUnionExtra"] = Processor.process_setUnionExtra
        self._processMap["deleteContributionPersonal"] = Processor.process_deleteContributionPersonal
        self._processMap["setRole"] = Processor.process_setRole
        self._processMap["unionLog"] = Processor.process_unionLog
        self._processMap["unionQuit"] = Processor.process_unionQuit
        self._on_message_begin = None

    def on_message_begin(self, func):
        self._on_message_begin = func

    def process(self, iprot, oprot):
        (name, type, seqid) = iprot.readMessageBegin()
        if self._on_message_begin:
            self._on_message_begin(name, type, seqid)
        if name not in self._processMap:
            iprot.skip(TType.STRUCT)
            iprot.readMessageEnd()
            x = TApplicationException(TApplicationException.UNKNOWN_METHOD, 'Unknown function %s' % (name))
            oprot.writeMessageBegin(name, TMessageType.EXCEPTION, seqid)
            x.write(oprot)
            oprot.writeMessageEnd()
            oprot.trans.flush()
            return
        else:
            self._processMap[name](self, seqid, iprot, oprot)
        return True

    def process_unionMembers(self, seqid, iprot, oprot):
        args = unionMembers_args()
        args.read(iprot)
        iprot.readMessageEnd()
        result = unionMembers_result()
        try:
            result.success = self._handler.unionMembers(args.normal, args.union_id)
            msg_type = TMessageType.REPLY
        except TTransport.TTransportException:
            raise
        except shared.ttypes.NormalException as normalException:
            msg_type = TMessageType.REPLY
            result.normalException = normalException
        except TApplicationException as ex:
            logging.exception('TApplication exception in handler')
            msg_type = TMessageType.EXCEPTION
            result = ex
        except Exception:
            logging.exception('Unexpected exception in handler')
            msg_type = TMessageType.EXCEPTION
            result = TApplicationException(TApplicationException.INTERNAL_ERROR, 'Internal error')
        oprot.writeMessageBegin("unionMembers", msg_type, seqid)
        result.write(oprot)
        oprot.writeMessageEnd()
        oprot.trans.flush()

    def process_unionInfo(self, seqid, iprot, oprot):
        args = unionInfo_args()
        args.read(iprot)
        iprot.readMessageEnd()
        result = unionInfo_result()
        try:
            result.success = self._handler.unionInfo(args.normal, args.union_id)
            msg_type = TMessageType.REPLY
        except TTransport.TTransportException:
            raise
        except shared.ttypes.NormalException as normalException:
            msg_type = TMessageType.REPLY
            result.normalException = normalException
        except TApplicationException as ex:
            logging.exception('TApplication exception in handler')
            msg_type = TMessageType.EXCEPTION
            result = ex
        except Exception:
            logging.exception('Unexpected exception in handler')
            msg_type = TMessageType.EXCEPTION
            result = TApplicationException(TApplicationException.INTERNAL_ERROR, 'Internal error')
        oprot.writeMessageBegin("unionInfo", msg_type, seqid)
        result.write(oprot)
        oprot.writeMessageEnd()
        oprot.trans.flush()

    def process_setMemberExtra(self, seqid, iprot, oprot):
        args = setMemberExtra_args()
        args.read(iprot)
        iprot.readMessageEnd()
        result = setMemberExtra_result()
        try:
            self._handler.setMemberExtra(args.normal, args.type, args.extra, args.union_id, args.uid, args.index)
            msg_type = TMessageType.REPLY
        except TTransport.TTransportException:
            raise
        except shared.ttypes.NormalException as normalException:
            msg_type = TMessageType.REPLY
            result.normalException = normalException
        except TApplicationException as ex:
            logging.exception('TApplication exception in handler')
            msg_type = TMessageType.EXCEPTION
            result = ex
        except Exception:
            logging.exception('Unexpected exception in handler')
            msg_type = TMessageType.EXCEPTION
            result = TApplicationException(TApplicationException.INTERNAL_ERROR, 'Internal error')
        oprot.writeMessageBegin("setMemberExtra", msg_type, seqid)
        result.write(oprot)
        oprot.writeMessageEnd()
        oprot.trans.flush()

    def process_setUnionExtra(self, seqid, iprot, oprot):
        args = setUnionExtra_args()
        args.read(iprot)
        iprot.readMessageEnd()
        result = setUnionExtra_result()
        try:
            self._handler.setUnionExtra(args.normal, args.type, args.extra, args.union_id)
            msg_type = TMessageType.REPLY
        except TTransport.TTransportException:
            raise
        except shared.ttypes.NormalException as normalException:
            msg_type = TMessageType.REPLY
            result.normalException = normalException
        except TApplicationException as ex:
            logging.exception('TApplication exception in handler')
            msg_type = TMessageType.EXCEPTION
            result = ex
        except Exception:
            logging.exception('Unexpected exception in handler')
            msg_type = TMessageType.EXCEPTION
            result = TApplicationException(TApplicationException.INTERNAL_ERROR, 'Internal error')
        oprot.writeMessageBegin("setUnionExtra", msg_type, seqid)
        result.write(oprot)
        oprot.writeMessageEnd()
        oprot.trans.flush()

    def process_deleteContributionPersonal(self, seqid, iprot, oprot):
        args = deleteContributionPersonal_args()
        args.read(iprot)
        iprot.readMessageEnd()
        result = deleteContributionPersonal_result()
        try:
            self._handler.deleteContributionPersonal(args.normal, args.contribution)
            msg_type = TMessageType.REPLY
        except TTransport.TTransportException:
            raise
        except shared.ttypes.NormalException as normalException:
            msg_type = TMessageType.REPLY
            result.normalException = normalException
        except TApplicationException as ex:
            logging.exception('TApplication exception in handler')
            msg_type = TMessageType.EXCEPTION
            result = ex
        except Exception:
            logging.exception('Unexpected exception in handler')
            msg_type = TMessageType.EXCEPTION
            result = TApplicationException(TApplicationException.INTERNAL_ERROR, 'Internal error')
        oprot.writeMessageBegin("deleteContributionPersonal", msg_type, seqid)
        result.write(oprot)
        oprot.writeMessageEnd()
        oprot.trans.flush()

    def process_setRole(self, seqid, iprot, oprot):
        args = setRole_args()
        args.read(iprot)
        iprot.readMessageEnd()
        result = setRole_result()
        try:
            self._handler.setRole(args.normal, args.uid, args.index, args.role_id)
            msg_type = TMessageType.REPLY
        except TTransport.TTransportException:
            raise
        except shared.ttypes.NormalException as normalException:
            msg_type = TMessageType.REPLY
            result.normalException = normalException
        except TApplicationException as ex:
            logging.exception('TApplication exception in handler')
            msg_type = TMessageType.EXCEPTION
            result = ex
        except Exception:
            logging.exception('Unexpected exception in handler')
            msg_type = TMessageType.EXCEPTION
            result = TApplicationException(TApplicationException.INTERNAL_ERROR, 'Internal error')
        oprot.writeMessageBegin("setRole", msg_type, seqid)
        result.write(oprot)
        oprot.writeMessageEnd()
        oprot.trans.flush()

    def process_unionLog(self, seqid, iprot, oprot):
        args = unionLog_args()
        args.read(iprot)
        iprot.readMessageEnd()
        result = unionLog_result()
        try:
            result.success = self._handler.unionLog(args.normal, args.page_num, args.page_size)
            msg_type = TMessageType.REPLY
        except TTransport.TTransportException:
            raise
        except shared.ttypes.NormalException as normalException:
            msg_type = TMessageType.REPLY
            result.normalException = normalException
        except TApplicationException as ex:
            logging.exception('TApplication exception in handler')
            msg_type = TMessageType.EXCEPTION
            result = ex
        except Exception:
            logging.exception('Unexpected exception in handler')
            msg_type = TMessageType.EXCEPTION
            result = TApplicationException(TApplicationException.INTERNAL_ERROR, 'Internal error')
        oprot.writeMessageBegin("unionLog", msg_type, seqid)
        result.write(oprot)
        oprot.writeMessageEnd()
        oprot.trans.flush()

    def process_unionQuit(self, seqid, iprot, oprot):
        args = unionQuit_args()
        args.read(iprot)
        iprot.readMessageEnd()
        result = unionQuit_result()
        try:
            self._handler.unionQuit(args.normal)
            msg_type = TMessageType.REPLY
        except TTransport.TTransportException:
            raise
        except shared.ttypes.NormalException as normalException:
            msg_type = TMessageType.REPLY
            result.normalException = normalException
        except TApplicationException as ex:
            logging.exception('TApplication exception in handler')
            msg_type = TMessageType.EXCEPTION
            result = ex
        except Exception:
            logging.exception('Unexpected exception in handler')
            msg_type = TMessageType.EXCEPTION
            result = TApplicationException(TApplicationException.INTERNAL_ERROR, 'Internal error')
        oprot.writeMessageBegin("unionQuit", msg_type, seqid)
        result.write(oprot)
        oprot.writeMessageEnd()
        oprot.trans.flush()

# HELPER FUNCTIONS AND STRUCTURES


class unionMembers_args(object):
    """
    Attributes:
     - normal
     - union_id

    """
    thrift_spec = None


    def __init__(self, normal = None, union_id = None,):
        self.normal = normal
        self.union_id = union_id

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.STRUCT:
                    self.normal = shared.ttypes.Normal()
                    self.normal.read(iprot)
                else:
                    iprot.skip(ftype)
            elif fid == 2:
                if ftype == TType.I32:
                    self.union_id = iprot.readI32()
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        self.validate()
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('unionMembers_args')
        if self.normal is not None:
            oprot.writeFieldBegin('normal', TType.STRUCT, 1)
            self.normal.write(oprot)
            oprot.writeFieldEnd()
        if self.union_id is not None:
            oprot.writeFieldBegin('union_id', TType.I32, 2)
            oprot.writeI32(self.union_id)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)
all_structs.append(unionMembers_args)
unionMembers_args.thrift_spec = (
    None,  # 0
    (1, TType.STRUCT, 'normal', [shared.ttypes.Normal, None], None, ),  # 1
    (2, TType.I32, 'union_id', None, None, ),  # 2
)


class unionMembers_result(object):
    """
    Attributes:
     - success
     - normalException

    """
    thrift_spec = None


    def __init__(self, success = None, normalException = None,):
        self.success = success
        self.normalException = normalException

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 0:
                if ftype == TType.STRUCT:
                    self.success = UnionMembers()
                    self.success.read(iprot)
                else:
                    iprot.skip(ftype)
            elif fid == 1:
                if ftype == TType.STRUCT:
                    self.normalException = shared.ttypes.NormalException.read(iprot)
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        self.validate()
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('unionMembers_result')
        if self.success is not None:
            oprot.writeFieldBegin('success', TType.STRUCT, 0)
            self.success.write(oprot)
            oprot.writeFieldEnd()
        if self.normalException is not None:
            oprot.writeFieldBegin('normalException', TType.STRUCT, 1)
            self.normalException.write(oprot)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)
all_structs.append(unionMembers_result)
unionMembers_result.thrift_spec = (
    (0, TType.STRUCT, 'success', [UnionMembers, None], None, ),  # 0
    (1, TType.STRUCT, 'normalException', [shared.ttypes.NormalException, None], None, ),  # 1
)


class unionInfo_args(object):
    """
    Attributes:
     - normal
     - union_id

    """
    thrift_spec = None


    def __init__(self, normal = None, union_id = None,):
        self.normal = normal
        self.union_id = union_id

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.STRUCT:
                    self.normal = shared.ttypes.Normal()
                    self.normal.read(iprot)
                else:
                    iprot.skip(ftype)
            elif fid == 2:
                if ftype == TType.I32:
                    self.union_id = iprot.readI32()
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        self.validate()
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('unionInfo_args')
        if self.normal is not None:
            oprot.writeFieldBegin('normal', TType.STRUCT, 1)
            self.normal.write(oprot)
            oprot.writeFieldEnd()
        if self.union_id is not None:
            oprot.writeFieldBegin('union_id', TType.I32, 2)
            oprot.writeI32(self.union_id)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)
all_structs.append(unionInfo_args)
unionInfo_args.thrift_spec = (
    None,  # 0
    (1, TType.STRUCT, 'normal', [shared.ttypes.Normal, None], None, ),  # 1
    (2, TType.I32, 'union_id', None, None, ),  # 2
)


class unionInfo_result(object):
    """
    Attributes:
     - success
     - normalException

    """
    thrift_spec = None


    def __init__(self, success = None, normalException = None,):
        self.success = success
        self.normalException = normalException

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 0:
                if ftype == TType.STRUCT:
                    self.success = UnionInfo()
                    self.success.read(iprot)
                else:
                    iprot.skip(ftype)
            elif fid == 1:
                if ftype == TType.STRUCT:
                    self.normalException = shared.ttypes.NormalException.read(iprot)
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        self.validate()
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('unionInfo_result')
        if self.success is not None:
            oprot.writeFieldBegin('success', TType.STRUCT, 0)
            self.success.write(oprot)
            oprot.writeFieldEnd()
        if self.normalException is not None:
            oprot.writeFieldBegin('normalException', TType.STRUCT, 1)
            self.normalException.write(oprot)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)
all_structs.append(unionInfo_result)
unionInfo_result.thrift_spec = (
    (0, TType.STRUCT, 'success', [UnionInfo, None], None, ),  # 0
    (1, TType.STRUCT, 'normalException', [shared.ttypes.NormalException, None], None, ),  # 1
)


class setMemberExtra_args(object):
    """
    Attributes:
     - normal
     - type
     - extra
     - union_id
     - uid
     - index

    """
    thrift_spec = None


    def __init__(self, normal = None, type = None, extra = None, union_id = None, uid = None, index = None,):
        self.normal = normal
        self.type = type
        self.extra = extra
        self.union_id = union_id
        self.uid = uid
        self.index = index

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.STRUCT:
                    self.normal = shared.ttypes.Normal()
                    self.normal.read(iprot)
                else:
                    iprot.skip(ftype)
            elif fid == 2:
                if ftype == TType.I32:
                    self.type = iprot.readI32()
                else:
                    iprot.skip(ftype)
            elif fid == 3:
                if ftype == TType.STRING:
                    self.extra = iprot.readString().decode('utf-8', errors='replace') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            elif fid == 4:
                if ftype == TType.I32:
                    self.union_id = iprot.readI32()
                else:
                    iprot.skip(ftype)
            elif fid == 5:
                if ftype == TType.I32:
                    self.uid = iprot.readI32()
                else:
                    iprot.skip(ftype)
            elif fid == 6:
                if ftype == TType.I32:
                    self.index = iprot.readI32()
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        self.validate()
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('setMemberExtra_args')
        if self.normal is not None:
            oprot.writeFieldBegin('normal', TType.STRUCT, 1)
            self.normal.write(oprot)
            oprot.writeFieldEnd()
        if self.type is not None:
            oprot.writeFieldBegin('type', TType.I32, 2)
            oprot.writeI32(self.type)
            oprot.writeFieldEnd()
        if self.extra is not None:
            oprot.writeFieldBegin('extra', TType.STRING, 3)
            oprot.writeString(self.extra.encode('utf-8') if sys.version_info[0] == 2 else self.extra)
            oprot.writeFieldEnd()
        if self.union_id is not None:
            oprot.writeFieldBegin('union_id', TType.I32, 4)
            oprot.writeI32(self.union_id)
            oprot.writeFieldEnd()
        if self.uid is not None:
            oprot.writeFieldBegin('uid', TType.I32, 5)
            oprot.writeI32(self.uid)
            oprot.writeFieldEnd()
        if self.index is not None:
            oprot.writeFieldBegin('index', TType.I32, 6)
            oprot.writeI32(self.index)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)
all_structs.append(setMemberExtra_args)
setMemberExtra_args.thrift_spec = (
    None,  # 0
    (1, TType.STRUCT, 'normal', [shared.ttypes.Normal, None], None, ),  # 1
    (2, TType.I32, 'type', None, None, ),  # 2
    (3, TType.STRING, 'extra', 'UTF8', None, ),  # 3
    (4, TType.I32, 'union_id', None, None, ),  # 4
    (5, TType.I32, 'uid', None, None, ),  # 5
    (6, TType.I32, 'index', None, None, ),  # 6
)


class setMemberExtra_result(object):
    """
    Attributes:
     - normalException

    """
    thrift_spec = None


    def __init__(self, normalException = None,):
        self.normalException = normalException

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.STRUCT:
                    self.normalException = shared.ttypes.NormalException.read(iprot)
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        self.validate()
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('setMemberExtra_result')
        if self.normalException is not None:
            oprot.writeFieldBegin('normalException', TType.STRUCT, 1)
            self.normalException.write(oprot)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)
all_structs.append(setMemberExtra_result)
setMemberExtra_result.thrift_spec = (
    None,  # 0
    (1, TType.STRUCT, 'normalException', [shared.ttypes.NormalException, None], None, ),  # 1
)


class setUnionExtra_args(object):
    """
    Attributes:
     - normal
     - type
     - extra
     - union_id

    """
    thrift_spec = None


    def __init__(self, normal = None, type = None, extra = None, union_id = None,):
        self.normal = normal
        self.type = type
        self.extra = extra
        self.union_id = union_id

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.STRUCT:
                    self.normal = shared.ttypes.Normal()
                    self.normal.read(iprot)
                else:
                    iprot.skip(ftype)
            elif fid == 2:
                if ftype == TType.I32:
                    self.type = iprot.readI32()
                else:
                    iprot.skip(ftype)
            elif fid == 3:
                if ftype == TType.STRING:
                    self.extra = iprot.readString().decode('utf-8', errors='replace') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            elif fid == 4:
                if ftype == TType.I32:
                    self.union_id = iprot.readI32()
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        self.validate()
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('setUnionExtra_args')
        if self.normal is not None:
            oprot.writeFieldBegin('normal', TType.STRUCT, 1)
            self.normal.write(oprot)
            oprot.writeFieldEnd()
        if self.type is not None:
            oprot.writeFieldBegin('type', TType.I32, 2)
            oprot.writeI32(self.type)
            oprot.writeFieldEnd()
        if self.extra is not None:
            oprot.writeFieldBegin('extra', TType.STRING, 3)
            oprot.writeString(self.extra.encode('utf-8') if sys.version_info[0] == 2 else self.extra)
            oprot.writeFieldEnd()
        if self.union_id is not None:
            oprot.writeFieldBegin('union_id', TType.I32, 4)
            oprot.writeI32(self.union_id)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)
all_structs.append(setUnionExtra_args)
setUnionExtra_args.thrift_spec = (
    None,  # 0
    (1, TType.STRUCT, 'normal', [shared.ttypes.Normal, None], None, ),  # 1
    (2, TType.I32, 'type', None, None, ),  # 2
    (3, TType.STRING, 'extra', 'UTF8', None, ),  # 3
    (4, TType.I32, 'union_id', None, None, ),  # 4
)


class setUnionExtra_result(object):
    """
    Attributes:
     - normalException

    """
    thrift_spec = None


    def __init__(self, normalException = None,):
        self.normalException = normalException

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.STRUCT:
                    self.normalException = shared.ttypes.NormalException.read(iprot)
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        self.validate()
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('setUnionExtra_result')
        if self.normalException is not None:
            oprot.writeFieldBegin('normalException', TType.STRUCT, 1)
            self.normalException.write(oprot)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)
all_structs.append(setUnionExtra_result)
setUnionExtra_result.thrift_spec = (
    None,  # 0
    (1, TType.STRUCT, 'normalException', [shared.ttypes.NormalException, None], None, ),  # 1
)


class deleteContributionPersonal_args(object):
    """
    Attributes:
     - normal
     - contribution

    """
    thrift_spec = None


    def __init__(self, normal = None, contribution = None,):
        self.normal = normal
        self.contribution = contribution

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.STRUCT:
                    self.normal = shared.ttypes.Normal()
                    self.normal.read(iprot)
                else:
                    iprot.skip(ftype)
            elif fid == 2:
                if ftype == TType.I32:
                    self.contribution = iprot.readI32()
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        self.validate()
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('deleteContributionPersonal_args')
        if self.normal is not None:
            oprot.writeFieldBegin('normal', TType.STRUCT, 1)
            self.normal.write(oprot)
            oprot.writeFieldEnd()
        if self.contribution is not None:
            oprot.writeFieldBegin('contribution', TType.I32, 2)
            oprot.writeI32(self.contribution)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)
all_structs.append(deleteContributionPersonal_args)
deleteContributionPersonal_args.thrift_spec = (
    None,  # 0
    (1, TType.STRUCT, 'normal', [shared.ttypes.Normal, None], None, ),  # 1
    (2, TType.I32, 'contribution', None, None, ),  # 2
)


class deleteContributionPersonal_result(object):
    """
    Attributes:
     - normalException

    """
    thrift_spec = None


    def __init__(self, normalException = None,):
        self.normalException = normalException

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.STRUCT:
                    self.normalException = shared.ttypes.NormalException.read(iprot)
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        self.validate()
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('deleteContributionPersonal_result')
        if self.normalException is not None:
            oprot.writeFieldBegin('normalException', TType.STRUCT, 1)
            self.normalException.write(oprot)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)
all_structs.append(deleteContributionPersonal_result)
deleteContributionPersonal_result.thrift_spec = (
    None,  # 0
    (1, TType.STRUCT, 'normalException', [shared.ttypes.NormalException, None], None, ),  # 1
)


class setRole_args(object):
    """
    Attributes:
     - normal
     - uid
     - index
     - role_id

    """
    thrift_spec = None


    def __init__(self, normal = None, uid = None, index = None, role_id = None,):
        self.normal = normal
        self.uid = uid
        self.index = index
        self.role_id = role_id

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.STRUCT:
                    self.normal = shared.ttypes.Normal()
                    self.normal.read(iprot)
                else:
                    iprot.skip(ftype)
            elif fid == 2:
                if ftype == TType.I32:
                    self.uid = iprot.readI32()
                else:
                    iprot.skip(ftype)
            elif fid == 3:
                if ftype == TType.I32:
                    self.index = iprot.readI32()
                else:
                    iprot.skip(ftype)
            elif fid == 4:
                if ftype == TType.I32:
                    self.role_id = iprot.readI32()
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        self.validate()
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('setRole_args')
        if self.normal is not None:
            oprot.writeFieldBegin('normal', TType.STRUCT, 1)
            self.normal.write(oprot)
            oprot.writeFieldEnd()
        if self.uid is not None:
            oprot.writeFieldBegin('uid', TType.I32, 2)
            oprot.writeI32(self.uid)
            oprot.writeFieldEnd()
        if self.index is not None:
            oprot.writeFieldBegin('index', TType.I32, 3)
            oprot.writeI32(self.index)
            oprot.writeFieldEnd()
        if self.role_id is not None:
            oprot.writeFieldBegin('role_id', TType.I32, 4)
            oprot.writeI32(self.role_id)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)
all_structs.append(setRole_args)
setRole_args.thrift_spec = (
    None,  # 0
    (1, TType.STRUCT, 'normal', [shared.ttypes.Normal, None], None, ),  # 1
    (2, TType.I32, 'uid', None, None, ),  # 2
    (3, TType.I32, 'index', None, None, ),  # 3
    (4, TType.I32, 'role_id', None, None, ),  # 4
)


class setRole_result(object):
    """
    Attributes:
     - normalException

    """
    thrift_spec = None


    def __init__(self, normalException = None,):
        self.normalException = normalException

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.STRUCT:
                    self.normalException = shared.ttypes.NormalException.read(iprot)
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        self.validate()
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('setRole_result')
        if self.normalException is not None:
            oprot.writeFieldBegin('normalException', TType.STRUCT, 1)
            self.normalException.write(oprot)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)
all_structs.append(setRole_result)
setRole_result.thrift_spec = (
    None,  # 0
    (1, TType.STRUCT, 'normalException', [shared.ttypes.NormalException, None], None, ),  # 1
)


class unionLog_args(object):
    """
    Attributes:
     - normal
     - page_num
     - page_size

    """
    thrift_spec = None


    def __init__(self, normal = None, page_num = None, page_size = None,):
        self.normal = normal
        self.page_num = page_num
        self.page_size = page_size

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.STRUCT:
                    self.normal = shared.ttypes.Normal()
                    self.normal.read(iprot)
                else:
                    iprot.skip(ftype)
            elif fid == 2:
                if ftype == TType.I32:
                    self.page_num = iprot.readI32()
                else:
                    iprot.skip(ftype)
            elif fid == 3:
                if ftype == TType.I32:
                    self.page_size = iprot.readI32()
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        self.validate()
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('unionLog_args')
        if self.normal is not None:
            oprot.writeFieldBegin('normal', TType.STRUCT, 1)
            self.normal.write(oprot)
            oprot.writeFieldEnd()
        if self.page_num is not None:
            oprot.writeFieldBegin('page_num', TType.I32, 2)
            oprot.writeI32(self.page_num)
            oprot.writeFieldEnd()
        if self.page_size is not None:
            oprot.writeFieldBegin('page_size', TType.I32, 3)
            oprot.writeI32(self.page_size)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)
all_structs.append(unionLog_args)
unionLog_args.thrift_spec = (
    None,  # 0
    (1, TType.STRUCT, 'normal', [shared.ttypes.Normal, None], None, ),  # 1
    (2, TType.I32, 'page_num', None, None, ),  # 2
    (3, TType.I32, 'page_size', None, None, ),  # 3
)


class unionLog_result(object):
    """
    Attributes:
     - success
     - normalException

    """
    thrift_spec = None


    def __init__(self, success = None, normalException = None,):
        self.success = success
        self.normalException = normalException

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 0:
                if ftype == TType.STRUCT:
                    self.success = LogInfo()
                    self.success.read(iprot)
                else:
                    iprot.skip(ftype)
            elif fid == 1:
                if ftype == TType.STRUCT:
                    self.normalException = shared.ttypes.NormalException.read(iprot)
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        self.validate()
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('unionLog_result')
        if self.success is not None:
            oprot.writeFieldBegin('success', TType.STRUCT, 0)
            self.success.write(oprot)
            oprot.writeFieldEnd()
        if self.normalException is not None:
            oprot.writeFieldBegin('normalException', TType.STRUCT, 1)
            self.normalException.write(oprot)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)
all_structs.append(unionLog_result)
unionLog_result.thrift_spec = (
    (0, TType.STRUCT, 'success', [LogInfo, None], None, ),  # 0
    (1, TType.STRUCT, 'normalException', [shared.ttypes.NormalException, None], None, ),  # 1
)


class unionQuit_args(object):
    """
    Attributes:
     - normal

    """
    thrift_spec = None


    def __init__(self, normal = None,):
        self.normal = normal

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.STRUCT:
                    self.normal = shared.ttypes.Normal()
                    self.normal.read(iprot)
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        self.validate()
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('unionQuit_args')
        if self.normal is not None:
            oprot.writeFieldBegin('normal', TType.STRUCT, 1)
            self.normal.write(oprot)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)
all_structs.append(unionQuit_args)
unionQuit_args.thrift_spec = (
    None,  # 0
    (1, TType.STRUCT, 'normal', [shared.ttypes.Normal, None], None, ),  # 1
)


class unionQuit_result(object):
    """
    Attributes:
     - normalException

    """
    thrift_spec = None


    def __init__(self, normalException = None,):
        self.normalException = normalException

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.STRUCT:
                    self.normalException = shared.ttypes.NormalException.read(iprot)
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        self.validate()
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('unionQuit_result')
        if self.normalException is not None:
            oprot.writeFieldBegin('normalException', TType.STRUCT, 1)
            self.normalException.write(oprot)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)
all_structs.append(unionQuit_result)
unionQuit_result.thrift_spec = (
    None,  # 0
    (1, TType.STRUCT, 'normalException', [shared.ttypes.NormalException, None], None, ),  # 1
)
fix_spec(all_structs)
del all_structs
