#
# Autogenerated by Thrift Compiler (0.22.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py
#

from thrift.Thrift import TType, TMessageType, TFrozenDict, TException, TApplicationException
from thrift.protocol.TProtocol import TProtocolException
from thrift.TRecursive import fix_spec
from uuid import UUID

import sys
import logging
from .ttypes import *
from thrift.Thrift import TProcessor
from thrift.transport import TTransport
all_structs = []


class Iface(object):
    def applyList(self, normal, page, page_size):
        """
        @description 获取军队成员申请列表
        @param normal API请求基础信息
        @param page 第几页
        @param page_size 每页条数
        @returns ApplyList 申请列表信息
        @throws NormalException 获取申请列表时可能抛出的异常

        Parameters:
         - normal
         - page
         - page_size

        """
        pass

    def applyAudit(self, normal, uid, index, audit_result):
        """
        @description 对军队成员申请进行审核，通过或拒绝申请
        @param normal API请求基础信息
        @param uid 被审核用户id
        @param index 被审核用户存档索引
        @param audit_result 审核结果 (0:拒绝, 1:通过)
        @throws NormalException 审核申请时可能抛出的异常

        Parameters:
         - normal
         - uid
         - index
         - audit_result

        """
        pass

    def memberRemove(self, normal, uid, index):
        """
        @description 将指定用户从军队中移除
        @param normal API请求基础信息
        @param uid 被移除用户uid
        @param index 被移除用户存档索引
        @throws NormalException 移除成员时可能抛出的异常

        Parameters:
         - normal
         - uid
         - index

        """
        pass

    def dissolve(self, normal, action_type):
        """
        @description 解散军队操作，72小时后生效
        @param normal API请求基础信息
        @param action_type 操作类型 (0:取消解散, 1:解散)
        @throws NormalException 解散军队时可能抛出的异常

        Parameters:
         - normal
         - action_type

        """
        pass

    def deleteContributionUnion(self, normal, contribution):
        """
        @description 消耗指定数量的帮会贡献点数
        @param normal API请求基础信息
        @param contribution 要消耗的帮会贡献点数
        @throws NormalException 消耗贡献点时可能抛出的异常

        Parameters:
         - normal
         - contribution

        """
        pass

    def transfer(self, normal, uid, index, result):
        """
        @description 将当前用户的军队转让给指定用户
        @param normal API请求基础信息
        @param uid 要转让给的用户id
        @param index 要转让给的用户存档索引
        @param result 是否转让标识，0：取消转让，1：确定转让
        @throws NormalException 转让军队过程中可能抛出的异常

        Parameters:
         - normal
         - uid
         - index
         - result

        """
        pass


class Client(Iface):
    def __init__(self, iprot, oprot=None):
        self._iprot = self._oprot = iprot
        if oprot is not None:
            self._oprot = oprot
        self._seqid = 0

    def applyList(self, normal, page, page_size):
        """
        @description 获取军队成员申请列表
        @param normal API请求基础信息
        @param page 第几页
        @param page_size 每页条数
        @returns ApplyList 申请列表信息
        @throws NormalException 获取申请列表时可能抛出的异常

        Parameters:
         - normal
         - page
         - page_size

        """
        self.send_applyList(normal, page, page_size)
        return self.recv_applyList()

    def send_applyList(self, normal, page, page_size):
        self._oprot.writeMessageBegin('applyList', TMessageType.CALL, self._seqid)
        args = applyList_args()
        args.normal = normal
        args.page = page
        args.page_size = page_size
        args.write(self._oprot)
        self._oprot.writeMessageEnd()
        self._oprot.trans.flush()

    def recv_applyList(self):
        iprot = self._iprot
        (fname, mtype, rseqid) = iprot.readMessageBegin()
        if mtype == TMessageType.EXCEPTION:
            x = TApplicationException()
            x.read(iprot)
            iprot.readMessageEnd()
            raise x
        result = applyList_result()
        result.read(iprot)
        iprot.readMessageEnd()
        if result.success is not None:
            return result.success
        if result.normalException is not None:
            raise result.normalException
        raise TApplicationException(TApplicationException.MISSING_RESULT, "applyList failed: unknown result")

    def applyAudit(self, normal, uid, index, audit_result):
        """
        @description 对军队成员申请进行审核，通过或拒绝申请
        @param normal API请求基础信息
        @param uid 被审核用户id
        @param index 被审核用户存档索引
        @param audit_result 审核结果 (0:拒绝, 1:通过)
        @throws NormalException 审核申请时可能抛出的异常

        Parameters:
         - normal
         - uid
         - index
         - audit_result

        """
        self.send_applyAudit(normal, uid, index, audit_result)
        self.recv_applyAudit()

    def send_applyAudit(self, normal, uid, index, audit_result):
        self._oprot.writeMessageBegin('applyAudit', TMessageType.CALL, self._seqid)
        args = applyAudit_args()
        args.normal = normal
        args.uid = uid
        args.index = index
        args.audit_result = audit_result
        args.write(self._oprot)
        self._oprot.writeMessageEnd()
        self._oprot.trans.flush()

    def recv_applyAudit(self):
        iprot = self._iprot
        (fname, mtype, rseqid) = iprot.readMessageBegin()
        if mtype == TMessageType.EXCEPTION:
            x = TApplicationException()
            x.read(iprot)
            iprot.readMessageEnd()
            raise x
        result = applyAudit_result()
        result.read(iprot)
        iprot.readMessageEnd()
        if result.normalException is not None:
            raise result.normalException
        return

    def memberRemove(self, normal, uid, index):
        """
        @description 将指定用户从军队中移除
        @param normal API请求基础信息
        @param uid 被移除用户uid
        @param index 被移除用户存档索引
        @throws NormalException 移除成员时可能抛出的异常

        Parameters:
         - normal
         - uid
         - index

        """
        self.send_memberRemove(normal, uid, index)
        self.recv_memberRemove()

    def send_memberRemove(self, normal, uid, index):
        self._oprot.writeMessageBegin('memberRemove', TMessageType.CALL, self._seqid)
        args = memberRemove_args()
        args.normal = normal
        args.uid = uid
        args.index = index
        args.write(self._oprot)
        self._oprot.writeMessageEnd()
        self._oprot.trans.flush()

    def recv_memberRemove(self):
        iprot = self._iprot
        (fname, mtype, rseqid) = iprot.readMessageBegin()
        if mtype == TMessageType.EXCEPTION:
            x = TApplicationException()
            x.read(iprot)
            iprot.readMessageEnd()
            raise x
        result = memberRemove_result()
        result.read(iprot)
        iprot.readMessageEnd()
        if result.normalException is not None:
            raise result.normalException
        return

    def dissolve(self, normal, action_type):
        """
        @description 解散军队操作，72小时后生效
        @param normal API请求基础信息
        @param action_type 操作类型 (0:取消解散, 1:解散)
        @throws NormalException 解散军队时可能抛出的异常

        Parameters:
         - normal
         - action_type

        """
        self.send_dissolve(normal, action_type)
        self.recv_dissolve()

    def send_dissolve(self, normal, action_type):
        self._oprot.writeMessageBegin('dissolve', TMessageType.CALL, self._seqid)
        args = dissolve_args()
        args.normal = normal
        args.action_type = action_type
        args.write(self._oprot)
        self._oprot.writeMessageEnd()
        self._oprot.trans.flush()

    def recv_dissolve(self):
        iprot = self._iprot
        (fname, mtype, rseqid) = iprot.readMessageBegin()
        if mtype == TMessageType.EXCEPTION:
            x = TApplicationException()
            x.read(iprot)
            iprot.readMessageEnd()
            raise x
        result = dissolve_result()
        result.read(iprot)
        iprot.readMessageEnd()
        if result.normalException is not None:
            raise result.normalException
        return

    def deleteContributionUnion(self, normal, contribution):
        """
        @description 消耗指定数量的帮会贡献点数
        @param normal API请求基础信息
        @param contribution 要消耗的帮会贡献点数
        @throws NormalException 消耗贡献点时可能抛出的异常

        Parameters:
         - normal
         - contribution

        """
        self.send_deleteContributionUnion(normal, contribution)
        self.recv_deleteContributionUnion()

    def send_deleteContributionUnion(self, normal, contribution):
        self._oprot.writeMessageBegin('deleteContributionUnion', TMessageType.CALL, self._seqid)
        args = deleteContributionUnion_args()
        args.normal = normal
        args.contribution = contribution
        args.write(self._oprot)
        self._oprot.writeMessageEnd()
        self._oprot.trans.flush()

    def recv_deleteContributionUnion(self):
        iprot = self._iprot
        (fname, mtype, rseqid) = iprot.readMessageBegin()
        if mtype == TMessageType.EXCEPTION:
            x = TApplicationException()
            x.read(iprot)
            iprot.readMessageEnd()
            raise x
        result = deleteContributionUnion_result()
        result.read(iprot)
        iprot.readMessageEnd()
        if result.normalException is not None:
            raise result.normalException
        return

    def transfer(self, normal, uid, index, result):
        """
        @description 将当前用户的军队转让给指定用户
        @param normal API请求基础信息
        @param uid 要转让给的用户id
        @param index 要转让给的用户存档索引
        @param result 是否转让标识，0：取消转让，1：确定转让
        @throws NormalException 转让军队过程中可能抛出的异常

        Parameters:
         - normal
         - uid
         - index
         - result

        """
        self.send_transfer(normal, uid, index, result)
        self.recv_transfer()

    def send_transfer(self, normal, uid, index, result):
        self._oprot.writeMessageBegin('transfer', TMessageType.CALL, self._seqid)
        args = transfer_args()
        args.normal = normal
        args.uid = uid
        args.index = index
        args.result = result
        args.write(self._oprot)
        self._oprot.writeMessageEnd()
        self._oprot.trans.flush()

    def recv_transfer(self):
        iprot = self._iprot
        (fname, mtype, rseqid) = iprot.readMessageBegin()
        if mtype == TMessageType.EXCEPTION:
            x = TApplicationException()
            x.read(iprot)
            iprot.readMessageEnd()
            raise x
        result = transfer_result()
        result.read(iprot)
        iprot.readMessageEnd()
        if result.normalException is not None:
            raise result.normalException
        return


class Processor(Iface, TProcessor):
    def __init__(self, handler):
        self._handler = handler
        self._processMap = {}
        self._processMap["applyList"] = Processor.process_applyList
        self._processMap["applyAudit"] = Processor.process_applyAudit
        self._processMap["memberRemove"] = Processor.process_memberRemove
        self._processMap["dissolve"] = Processor.process_dissolve
        self._processMap["deleteContributionUnion"] = Processor.process_deleteContributionUnion
        self._processMap["transfer"] = Processor.process_transfer
        self._on_message_begin = None

    def on_message_begin(self, func):
        self._on_message_begin = func

    def process(self, iprot, oprot):
        (name, type, seqid) = iprot.readMessageBegin()
        if self._on_message_begin:
            self._on_message_begin(name, type, seqid)
        if name not in self._processMap:
            iprot.skip(TType.STRUCT)
            iprot.readMessageEnd()
            x = TApplicationException(TApplicationException.UNKNOWN_METHOD, 'Unknown function %s' % (name))
            oprot.writeMessageBegin(name, TMessageType.EXCEPTION, seqid)
            x.write(oprot)
            oprot.writeMessageEnd()
            oprot.trans.flush()
            return
        else:
            self._processMap[name](self, seqid, iprot, oprot)
        return True

    def process_applyList(self, seqid, iprot, oprot):
        args = applyList_args()
        args.read(iprot)
        iprot.readMessageEnd()
        result = applyList_result()
        try:
            result.success = self._handler.applyList(args.normal, args.page, args.page_size)
            msg_type = TMessageType.REPLY
        except TTransport.TTransportException:
            raise
        except shared.ttypes.NormalException as normalException:
            msg_type = TMessageType.REPLY
            result.normalException = normalException
        except TApplicationException as ex:
            logging.exception('TApplication exception in handler')
            msg_type = TMessageType.EXCEPTION
            result = ex
        except Exception:
            logging.exception('Unexpected exception in handler')
            msg_type = TMessageType.EXCEPTION
            result = TApplicationException(TApplicationException.INTERNAL_ERROR, 'Internal error')
        oprot.writeMessageBegin("applyList", msg_type, seqid)
        result.write(oprot)
        oprot.writeMessageEnd()
        oprot.trans.flush()

    def process_applyAudit(self, seqid, iprot, oprot):
        args = applyAudit_args()
        args.read(iprot)
        iprot.readMessageEnd()
        result = applyAudit_result()
        try:
            self._handler.applyAudit(args.normal, args.uid, args.index, args.audit_result)
            msg_type = TMessageType.REPLY
        except TTransport.TTransportException:
            raise
        except shared.ttypes.NormalException as normalException:
            msg_type = TMessageType.REPLY
            result.normalException = normalException
        except TApplicationException as ex:
            logging.exception('TApplication exception in handler')
            msg_type = TMessageType.EXCEPTION
            result = ex
        except Exception:
            logging.exception('Unexpected exception in handler')
            msg_type = TMessageType.EXCEPTION
            result = TApplicationException(TApplicationException.INTERNAL_ERROR, 'Internal error')
        oprot.writeMessageBegin("applyAudit", msg_type, seqid)
        result.write(oprot)
        oprot.writeMessageEnd()
        oprot.trans.flush()

    def process_memberRemove(self, seqid, iprot, oprot):
        args = memberRemove_args()
        args.read(iprot)
        iprot.readMessageEnd()
        result = memberRemove_result()
        try:
            self._handler.memberRemove(args.normal, args.uid, args.index)
            msg_type = TMessageType.REPLY
        except TTransport.TTransportException:
            raise
        except shared.ttypes.NormalException as normalException:
            msg_type = TMessageType.REPLY
            result.normalException = normalException
        except TApplicationException as ex:
            logging.exception('TApplication exception in handler')
            msg_type = TMessageType.EXCEPTION
            result = ex
        except Exception:
            logging.exception('Unexpected exception in handler')
            msg_type = TMessageType.EXCEPTION
            result = TApplicationException(TApplicationException.INTERNAL_ERROR, 'Internal error')
        oprot.writeMessageBegin("memberRemove", msg_type, seqid)
        result.write(oprot)
        oprot.writeMessageEnd()
        oprot.trans.flush()

    def process_dissolve(self, seqid, iprot, oprot):
        args = dissolve_args()
        args.read(iprot)
        iprot.readMessageEnd()
        result = dissolve_result()
        try:
            self._handler.dissolve(args.normal, args.action_type)
            msg_type = TMessageType.REPLY
        except TTransport.TTransportException:
            raise
        except shared.ttypes.NormalException as normalException:
            msg_type = TMessageType.REPLY
            result.normalException = normalException
        except TApplicationException as ex:
            logging.exception('TApplication exception in handler')
            msg_type = TMessageType.EXCEPTION
            result = ex
        except Exception:
            logging.exception('Unexpected exception in handler')
            msg_type = TMessageType.EXCEPTION
            result = TApplicationException(TApplicationException.INTERNAL_ERROR, 'Internal error')
        oprot.writeMessageBegin("dissolve", msg_type, seqid)
        result.write(oprot)
        oprot.writeMessageEnd()
        oprot.trans.flush()

    def process_deleteContributionUnion(self, seqid, iprot, oprot):
        args = deleteContributionUnion_args()
        args.read(iprot)
        iprot.readMessageEnd()
        result = deleteContributionUnion_result()
        try:
            self._handler.deleteContributionUnion(args.normal, args.contribution)
            msg_type = TMessageType.REPLY
        except TTransport.TTransportException:
            raise
        except shared.ttypes.NormalException as normalException:
            msg_type = TMessageType.REPLY
            result.normalException = normalException
        except TApplicationException as ex:
            logging.exception('TApplication exception in handler')
            msg_type = TMessageType.EXCEPTION
            result = ex
        except Exception:
            logging.exception('Unexpected exception in handler')
            msg_type = TMessageType.EXCEPTION
            result = TApplicationException(TApplicationException.INTERNAL_ERROR, 'Internal error')
        oprot.writeMessageBegin("deleteContributionUnion", msg_type, seqid)
        result.write(oprot)
        oprot.writeMessageEnd()
        oprot.trans.flush()

    def process_transfer(self, seqid, iprot, oprot):
        args = transfer_args()
        args.read(iprot)
        iprot.readMessageEnd()
        result = transfer_result()
        try:
            self._handler.transfer(args.normal, args.uid, args.index, args.result)
            msg_type = TMessageType.REPLY
        except TTransport.TTransportException:
            raise
        except shared.ttypes.NormalException as normalException:
            msg_type = TMessageType.REPLY
            result.normalException = normalException
        except TApplicationException as ex:
            logging.exception('TApplication exception in handler')
            msg_type = TMessageType.EXCEPTION
            result = ex
        except Exception:
            logging.exception('Unexpected exception in handler')
            msg_type = TMessageType.EXCEPTION
            result = TApplicationException(TApplicationException.INTERNAL_ERROR, 'Internal error')
        oprot.writeMessageBegin("transfer", msg_type, seqid)
        result.write(oprot)
        oprot.writeMessageEnd()
        oprot.trans.flush()

# HELPER FUNCTIONS AND STRUCTURES


class applyList_args(object):
    """
    Attributes:
     - normal
     - page
     - page_size

    """
    thrift_spec = None


    def __init__(self, normal = None, page = None, page_size = None,):
        self.normal = normal
        self.page = page
        self.page_size = page_size

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.STRUCT:
                    self.normal = shared.ttypes.Normal()
                    self.normal.read(iprot)
                else:
                    iprot.skip(ftype)
            elif fid == 2:
                if ftype == TType.I32:
                    self.page = iprot.readI32()
                else:
                    iprot.skip(ftype)
            elif fid == 3:
                if ftype == TType.I32:
                    self.page_size = iprot.readI32()
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        self.validate()
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('applyList_args')
        if self.normal is not None:
            oprot.writeFieldBegin('normal', TType.STRUCT, 1)
            self.normal.write(oprot)
            oprot.writeFieldEnd()
        if self.page is not None:
            oprot.writeFieldBegin('page', TType.I32, 2)
            oprot.writeI32(self.page)
            oprot.writeFieldEnd()
        if self.page_size is not None:
            oprot.writeFieldBegin('page_size', TType.I32, 3)
            oprot.writeI32(self.page_size)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)
all_structs.append(applyList_args)
applyList_args.thrift_spec = (
    None,  # 0
    (1, TType.STRUCT, 'normal', [shared.ttypes.Normal, None], None, ),  # 1
    (2, TType.I32, 'page', None, None, ),  # 2
    (3, TType.I32, 'page_size', None, None, ),  # 3
)


class applyList_result(object):
    """
    Attributes:
     - success
     - normalException

    """
    thrift_spec = None


    def __init__(self, success = None, normalException = None,):
        self.success = success
        self.normalException = normalException

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 0:
                if ftype == TType.STRUCT:
                    self.success = ApplyList()
                    self.success.read(iprot)
                else:
                    iprot.skip(ftype)
            elif fid == 1:
                if ftype == TType.STRUCT:
                    self.normalException = shared.ttypes.NormalException.read(iprot)
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        self.validate()
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('applyList_result')
        if self.success is not None:
            oprot.writeFieldBegin('success', TType.STRUCT, 0)
            self.success.write(oprot)
            oprot.writeFieldEnd()
        if self.normalException is not None:
            oprot.writeFieldBegin('normalException', TType.STRUCT, 1)
            self.normalException.write(oprot)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)
all_structs.append(applyList_result)
applyList_result.thrift_spec = (
    (0, TType.STRUCT, 'success', [ApplyList, None], None, ),  # 0
    (1, TType.STRUCT, 'normalException', [shared.ttypes.NormalException, None], None, ),  # 1
)


class applyAudit_args(object):
    """
    Attributes:
     - normal
     - uid
     - index
     - audit_result

    """
    thrift_spec = None


    def __init__(self, normal = None, uid = None, index = None, audit_result = None,):
        self.normal = normal
        self.uid = uid
        self.index = index
        self.audit_result = audit_result

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.STRUCT:
                    self.normal = shared.ttypes.Normal()
                    self.normal.read(iprot)
                else:
                    iprot.skip(ftype)
            elif fid == 2:
                if ftype == TType.I32:
                    self.uid = iprot.readI32()
                else:
                    iprot.skip(ftype)
            elif fid == 3:
                if ftype == TType.STRING:
                    self.index = iprot.readString().decode('utf-8', errors='replace') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            elif fid == 4:
                if ftype == TType.I32:
                    self.audit_result = iprot.readI32()
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        self.validate()
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('applyAudit_args')
        if self.normal is not None:
            oprot.writeFieldBegin('normal', TType.STRUCT, 1)
            self.normal.write(oprot)
            oprot.writeFieldEnd()
        if self.uid is not None:
            oprot.writeFieldBegin('uid', TType.I32, 2)
            oprot.writeI32(self.uid)
            oprot.writeFieldEnd()
        if self.index is not None:
            oprot.writeFieldBegin('index', TType.STRING, 3)
            oprot.writeString(self.index.encode('utf-8') if sys.version_info[0] == 2 else self.index)
            oprot.writeFieldEnd()
        if self.audit_result is not None:
            oprot.writeFieldBegin('audit_result', TType.I32, 4)
            oprot.writeI32(self.audit_result)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)
all_structs.append(applyAudit_args)
applyAudit_args.thrift_spec = (
    None,  # 0
    (1, TType.STRUCT, 'normal', [shared.ttypes.Normal, None], None, ),  # 1
    (2, TType.I32, 'uid', None, None, ),  # 2
    (3, TType.STRING, 'index', 'UTF8', None, ),  # 3
    (4, TType.I32, 'audit_result', None, None, ),  # 4
)


class applyAudit_result(object):
    """
    Attributes:
     - normalException

    """
    thrift_spec = None


    def __init__(self, normalException = None,):
        self.normalException = normalException

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.STRUCT:
                    self.normalException = shared.ttypes.NormalException.read(iprot)
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        self.validate()
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('applyAudit_result')
        if self.normalException is not None:
            oprot.writeFieldBegin('normalException', TType.STRUCT, 1)
            self.normalException.write(oprot)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)
all_structs.append(applyAudit_result)
applyAudit_result.thrift_spec = (
    None,  # 0
    (1, TType.STRUCT, 'normalException', [shared.ttypes.NormalException, None], None, ),  # 1
)


class memberRemove_args(object):
    """
    Attributes:
     - normal
     - uid
     - index

    """
    thrift_spec = None


    def __init__(self, normal = None, uid = None, index = None,):
        self.normal = normal
        self.uid = uid
        self.index = index

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.STRUCT:
                    self.normal = shared.ttypes.Normal()
                    self.normal.read(iprot)
                else:
                    iprot.skip(ftype)
            elif fid == 2:
                if ftype == TType.I32:
                    self.uid = iprot.readI32()
                else:
                    iprot.skip(ftype)
            elif fid == 3:
                if ftype == TType.STRING:
                    self.index = iprot.readString().decode('utf-8', errors='replace') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        self.validate()
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('memberRemove_args')
        if self.normal is not None:
            oprot.writeFieldBegin('normal', TType.STRUCT, 1)
            self.normal.write(oprot)
            oprot.writeFieldEnd()
        if self.uid is not None:
            oprot.writeFieldBegin('uid', TType.I32, 2)
            oprot.writeI32(self.uid)
            oprot.writeFieldEnd()
        if self.index is not None:
            oprot.writeFieldBegin('index', TType.STRING, 3)
            oprot.writeString(self.index.encode('utf-8') if sys.version_info[0] == 2 else self.index)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)
all_structs.append(memberRemove_args)
memberRemove_args.thrift_spec = (
    None,  # 0
    (1, TType.STRUCT, 'normal', [shared.ttypes.Normal, None], None, ),  # 1
    (2, TType.I32, 'uid', None, None, ),  # 2
    (3, TType.STRING, 'index', 'UTF8', None, ),  # 3
)


class memberRemove_result(object):
    """
    Attributes:
     - normalException

    """
    thrift_spec = None


    def __init__(self, normalException = None,):
        self.normalException = normalException

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.STRUCT:
                    self.normalException = shared.ttypes.NormalException.read(iprot)
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        self.validate()
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('memberRemove_result')
        if self.normalException is not None:
            oprot.writeFieldBegin('normalException', TType.STRUCT, 1)
            self.normalException.write(oprot)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)
all_structs.append(memberRemove_result)
memberRemove_result.thrift_spec = (
    None,  # 0
    (1, TType.STRUCT, 'normalException', [shared.ttypes.NormalException, None], None, ),  # 1
)


class dissolve_args(object):
    """
    Attributes:
     - normal
     - action_type

    """
    thrift_spec = None


    def __init__(self, normal = None, action_type = None,):
        self.normal = normal
        self.action_type = action_type

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.STRUCT:
                    self.normal = shared.ttypes.Normal()
                    self.normal.read(iprot)
                else:
                    iprot.skip(ftype)
            elif fid == 2:
                if ftype == TType.I32:
                    self.action_type = iprot.readI32()
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        self.validate()
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('dissolve_args')
        if self.normal is not None:
            oprot.writeFieldBegin('normal', TType.STRUCT, 1)
            self.normal.write(oprot)
            oprot.writeFieldEnd()
        if self.action_type is not None:
            oprot.writeFieldBegin('action_type', TType.I32, 2)
            oprot.writeI32(self.action_type)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)
all_structs.append(dissolve_args)
dissolve_args.thrift_spec = (
    None,  # 0
    (1, TType.STRUCT, 'normal', [shared.ttypes.Normal, None], None, ),  # 1
    (2, TType.I32, 'action_type', None, None, ),  # 2
)


class dissolve_result(object):
    """
    Attributes:
     - normalException

    """
    thrift_spec = None


    def __init__(self, normalException = None,):
        self.normalException = normalException

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.STRUCT:
                    self.normalException = shared.ttypes.NormalException.read(iprot)
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        self.validate()
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('dissolve_result')
        if self.normalException is not None:
            oprot.writeFieldBegin('normalException', TType.STRUCT, 1)
            self.normalException.write(oprot)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)
all_structs.append(dissolve_result)
dissolve_result.thrift_spec = (
    None,  # 0
    (1, TType.STRUCT, 'normalException', [shared.ttypes.NormalException, None], None, ),  # 1
)


class deleteContributionUnion_args(object):
    """
    Attributes:
     - normal
     - contribution

    """
    thrift_spec = None


    def __init__(self, normal = None, contribution = None,):
        self.normal = normal
        self.contribution = contribution

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.STRUCT:
                    self.normal = shared.ttypes.Normal()
                    self.normal.read(iprot)
                else:
                    iprot.skip(ftype)
            elif fid == 2:
                if ftype == TType.I32:
                    self.contribution = iprot.readI32()
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        self.validate()
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('deleteContributionUnion_args')
        if self.normal is not None:
            oprot.writeFieldBegin('normal', TType.STRUCT, 1)
            self.normal.write(oprot)
            oprot.writeFieldEnd()
        if self.contribution is not None:
            oprot.writeFieldBegin('contribution', TType.I32, 2)
            oprot.writeI32(self.contribution)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)
all_structs.append(deleteContributionUnion_args)
deleteContributionUnion_args.thrift_spec = (
    None,  # 0
    (1, TType.STRUCT, 'normal', [shared.ttypes.Normal, None], None, ),  # 1
    (2, TType.I32, 'contribution', None, None, ),  # 2
)


class deleteContributionUnion_result(object):
    """
    Attributes:
     - normalException

    """
    thrift_spec = None


    def __init__(self, normalException = None,):
        self.normalException = normalException

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.STRUCT:
                    self.normalException = shared.ttypes.NormalException.read(iprot)
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        self.validate()
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('deleteContributionUnion_result')
        if self.normalException is not None:
            oprot.writeFieldBegin('normalException', TType.STRUCT, 1)
            self.normalException.write(oprot)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)
all_structs.append(deleteContributionUnion_result)
deleteContributionUnion_result.thrift_spec = (
    None,  # 0
    (1, TType.STRUCT, 'normalException', [shared.ttypes.NormalException, None], None, ),  # 1
)


class transfer_args(object):
    """
    Attributes:
     - normal
     - uid
     - index
     - result

    """
    thrift_spec = None


    def __init__(self, normal = None, uid = None, index = None, result = None,):
        self.normal = normal
        self.uid = uid
        self.index = index
        self.result = result

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.STRUCT:
                    self.normal = shared.ttypes.Normal()
                    self.normal.read(iprot)
                else:
                    iprot.skip(ftype)
            elif fid == 2:
                if ftype == TType.I32:
                    self.uid = iprot.readI32()
                else:
                    iprot.skip(ftype)
            elif fid == 3:
                if ftype == TType.STRING:
                    self.index = iprot.readString().decode('utf-8', errors='replace') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            elif fid == 4:
                if ftype == TType.I32:
                    self.result = iprot.readI32()
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        self.validate()
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('transfer_args')
        if self.normal is not None:
            oprot.writeFieldBegin('normal', TType.STRUCT, 1)
            self.normal.write(oprot)
            oprot.writeFieldEnd()
        if self.uid is not None:
            oprot.writeFieldBegin('uid', TType.I32, 2)
            oprot.writeI32(self.uid)
            oprot.writeFieldEnd()
        if self.index is not None:
            oprot.writeFieldBegin('index', TType.STRING, 3)
            oprot.writeString(self.index.encode('utf-8') if sys.version_info[0] == 2 else self.index)
            oprot.writeFieldEnd()
        if self.result is not None:
            oprot.writeFieldBegin('result', TType.I32, 4)
            oprot.writeI32(self.result)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)
all_structs.append(transfer_args)
transfer_args.thrift_spec = (
    None,  # 0
    (1, TType.STRUCT, 'normal', [shared.ttypes.Normal, None], None, ),  # 1
    (2, TType.I32, 'uid', None, None, ),  # 2
    (3, TType.STRING, 'index', 'UTF8', None, ),  # 3
    (4, TType.I32, 'result', None, None, ),  # 4
)


class transfer_result(object):
    """
    Attributes:
     - normalException

    """
    thrift_spec = None


    def __init__(self, normalException = None,):
        self.normalException = normalException

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.STRUCT:
                    self.normalException = shared.ttypes.NormalException.read(iprot)
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        self.validate()
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('transfer_result')
        if self.normalException is not None:
            oprot.writeFieldBegin('normalException', TType.STRUCT, 1)
            self.normalException.write(oprot)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)
all_structs.append(transfer_result)
transfer_result.thrift_spec = (
    None,  # 0
    (1, TType.STRUCT, 'normalException', [shared.ttypes.NormalException, None], None, ),  # 1
)
fix_spec(all_structs)
del all_structs
