#
# Autogenerated by Thrift Compiler (0.22.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py
#

from thrift.Thrift import TType, TMessageType, TFrozenDict, TException, TApplicationException
from thrift.protocol.TProtocol import TProtocolException
from thrift.TRecursive import fix_spec
from uuid import UUID

import sys
import logging
from .ttypes import *
from thrift.Thrift import TProcessor
from thrift.transport import TTransport
all_structs = []


class Iface(object):
    def unionOfMe(self, normal):
        """
        @description 获取当前用户所在的军队以及用户的数据
        @param normal API请求基础信息
        @returns UnionOfMe 用户军队信息
          - time: string 时间戳
          - compose: Compose 军队和成员信息
        @throws NormalException 获取军队信息时可能抛出的异常

        Parameters:
         - normal

        """
        pass

    def unionList(self, normal, page_num, page_size):
        """
        @description 获取可加入的军队列表
        @param normal API请求基础信息
        @param page_num 第几页
        @param page_size 每页条数
        @returns UnionList 军队列表信息
          - time: string 时间戳
          - general_unions: list[GeneralUnion] 军队列表
        @throws NormalException 获取军队列表时可能抛出的异常

        Parameters:
         - normal
         - page_num
         - page_size

        """
        pass

    def unionCreate(self, normal, title, extra):
        """
        @description 创建一个新的军队
        @param normal API请求基础信息
        @param title 帮会名称
        @param extra 军队扩展信息
        @throws NormalException 创建军队时可能抛出的异常

        Parameters:
         - normal
         - title
         - extra

        """
        pass

    def unionApply(self, normal, union_id, extra):
        """
        @description 申请加入指定的军队
        @param normal API请求基础信息
        @param union_id 帮会id
        @param extra 申请人扩展信息
        @throws NormalException 申请军队时可能抛出的异常

        Parameters:
         - normal
         - union_id
         - extra

        """
        pass


class Client(Iface):
    def __init__(self, iprot, oprot=None):
        self._iprot = self._oprot = iprot
        if oprot is not None:
            self._oprot = oprot
        self._seqid = 0

    def unionOfMe(self, normal):
        """
        @description 获取当前用户所在的军队以及用户的数据
        @param normal API请求基础信息
        @returns UnionOfMe 用户军队信息
          - time: string 时间戳
          - compose: Compose 军队和成员信息
        @throws NormalException 获取军队信息时可能抛出的异常

        Parameters:
         - normal

        """
        self.send_unionOfMe(normal)
        return self.recv_unionOfMe()

    def send_unionOfMe(self, normal):
        self._oprot.writeMessageBegin('unionOfMe', TMessageType.CALL, self._seqid)
        args = unionOfMe_args()
        args.normal = normal
        args.write(self._oprot)
        self._oprot.writeMessageEnd()
        self._oprot.trans.flush()

    def recv_unionOfMe(self):
        iprot = self._iprot
        (fname, mtype, rseqid) = iprot.readMessageBegin()
        if mtype == TMessageType.EXCEPTION:
            x = TApplicationException()
            x.read(iprot)
            iprot.readMessageEnd()
            raise x
        result = unionOfMe_result()
        result.read(iprot)
        iprot.readMessageEnd()
        if result.success is not None:
            return result.success
        if result.normalException is not None:
            raise result.normalException
        raise TApplicationException(TApplicationException.MISSING_RESULT, "unionOfMe failed: unknown result")

    def unionList(self, normal, page_num, page_size):
        """
        @description 获取可加入的军队列表
        @param normal API请求基础信息
        @param page_num 第几页
        @param page_size 每页条数
        @returns UnionList 军队列表信息
          - time: string 时间戳
          - general_unions: list[GeneralUnion] 军队列表
        @throws NormalException 获取军队列表时可能抛出的异常

        Parameters:
         - normal
         - page_num
         - page_size

        """
        self.send_unionList(normal, page_num, page_size)
        return self.recv_unionList()

    def send_unionList(self, normal, page_num, page_size):
        self._oprot.writeMessageBegin('unionList', TMessageType.CALL, self._seqid)
        args = unionList_args()
        args.normal = normal
        args.page_num = page_num
        args.page_size = page_size
        args.write(self._oprot)
        self._oprot.writeMessageEnd()
        self._oprot.trans.flush()

    def recv_unionList(self):
        iprot = self._iprot
        (fname, mtype, rseqid) = iprot.readMessageBegin()
        if mtype == TMessageType.EXCEPTION:
            x = TApplicationException()
            x.read(iprot)
            iprot.readMessageEnd()
            raise x
        result = unionList_result()
        result.read(iprot)
        iprot.readMessageEnd()
        if result.success is not None:
            return result.success
        if result.normalException is not None:
            raise result.normalException
        raise TApplicationException(TApplicationException.MISSING_RESULT, "unionList failed: unknown result")

    def unionCreate(self, normal, title, extra):
        """
        @description 创建一个新的军队
        @param normal API请求基础信息
        @param title 帮会名称
        @param extra 军队扩展信息
        @throws NormalException 创建军队时可能抛出的异常

        Parameters:
         - normal
         - title
         - extra

        """
        self.send_unionCreate(normal, title, extra)
        self.recv_unionCreate()

    def send_unionCreate(self, normal, title, extra):
        self._oprot.writeMessageBegin('unionCreate', TMessageType.CALL, self._seqid)
        args = unionCreate_args()
        args.normal = normal
        args.title = title
        args.extra = extra
        args.write(self._oprot)
        self._oprot.writeMessageEnd()
        self._oprot.trans.flush()

    def recv_unionCreate(self):
        iprot = self._iprot
        (fname, mtype, rseqid) = iprot.readMessageBegin()
        if mtype == TMessageType.EXCEPTION:
            x = TApplicationException()
            x.read(iprot)
            iprot.readMessageEnd()
            raise x
        result = unionCreate_result()
        result.read(iprot)
        iprot.readMessageEnd()
        if result.normalException is not None:
            raise result.normalException
        return

    def unionApply(self, normal, union_id, extra):
        """
        @description 申请加入指定的军队
        @param normal API请求基础信息
        @param union_id 帮会id
        @param extra 申请人扩展信息
        @throws NormalException 申请军队时可能抛出的异常

        Parameters:
         - normal
         - union_id
         - extra

        """
        self.send_unionApply(normal, union_id, extra)
        self.recv_unionApply()

    def send_unionApply(self, normal, union_id, extra):
        self._oprot.writeMessageBegin('unionApply', TMessageType.CALL, self._seqid)
        args = unionApply_args()
        args.normal = normal
        args.union_id = union_id
        args.extra = extra
        args.write(self._oprot)
        self._oprot.writeMessageEnd()
        self._oprot.trans.flush()

    def recv_unionApply(self):
        iprot = self._iprot
        (fname, mtype, rseqid) = iprot.readMessageBegin()
        if mtype == TMessageType.EXCEPTION:
            x = TApplicationException()
            x.read(iprot)
            iprot.readMessageEnd()
            raise x
        result = unionApply_result()
        result.read(iprot)
        iprot.readMessageEnd()
        if result.normalException is not None:
            raise result.normalException
        return


class Processor(Iface, TProcessor):
    def __init__(self, handler):
        self._handler = handler
        self._processMap = {}
        self._processMap["unionOfMe"] = Processor.process_unionOfMe
        self._processMap["unionList"] = Processor.process_unionList
        self._processMap["unionCreate"] = Processor.process_unionCreate
        self._processMap["unionApply"] = Processor.process_unionApply
        self._on_message_begin = None

    def on_message_begin(self, func):
        self._on_message_begin = func

    def process(self, iprot, oprot):
        (name, type, seqid) = iprot.readMessageBegin()
        if self._on_message_begin:
            self._on_message_begin(name, type, seqid)
        if name not in self._processMap:
            iprot.skip(TType.STRUCT)
            iprot.readMessageEnd()
            x = TApplicationException(TApplicationException.UNKNOWN_METHOD, 'Unknown function %s' % (name))
            oprot.writeMessageBegin(name, TMessageType.EXCEPTION, seqid)
            x.write(oprot)
            oprot.writeMessageEnd()
            oprot.trans.flush()
            return
        else:
            self._processMap[name](self, seqid, iprot, oprot)
        return True

    def process_unionOfMe(self, seqid, iprot, oprot):
        args = unionOfMe_args()
        args.read(iprot)
        iprot.readMessageEnd()
        result = unionOfMe_result()
        try:
            result.success = self._handler.unionOfMe(args.normal)
            msg_type = TMessageType.REPLY
        except TTransport.TTransportException:
            raise
        except shared.ttypes.NormalException as normalException:
            msg_type = TMessageType.REPLY
            result.normalException = normalException
        except TApplicationException as ex:
            logging.exception('TApplication exception in handler')
            msg_type = TMessageType.EXCEPTION
            result = ex
        except Exception:
            logging.exception('Unexpected exception in handler')
            msg_type = TMessageType.EXCEPTION
            result = TApplicationException(TApplicationException.INTERNAL_ERROR, 'Internal error')
        oprot.writeMessageBegin("unionOfMe", msg_type, seqid)
        result.write(oprot)
        oprot.writeMessageEnd()
        oprot.trans.flush()

    def process_unionList(self, seqid, iprot, oprot):
        args = unionList_args()
        args.read(iprot)
        iprot.readMessageEnd()
        result = unionList_result()
        try:
            result.success = self._handler.unionList(args.normal, args.page_num, args.page_size)
            msg_type = TMessageType.REPLY
        except TTransport.TTransportException:
            raise
        except shared.ttypes.NormalException as normalException:
            msg_type = TMessageType.REPLY
            result.normalException = normalException
        except TApplicationException as ex:
            logging.exception('TApplication exception in handler')
            msg_type = TMessageType.EXCEPTION
            result = ex
        except Exception:
            logging.exception('Unexpected exception in handler')
            msg_type = TMessageType.EXCEPTION
            result = TApplicationException(TApplicationException.INTERNAL_ERROR, 'Internal error')
        oprot.writeMessageBegin("unionList", msg_type, seqid)
        result.write(oprot)
        oprot.writeMessageEnd()
        oprot.trans.flush()

    def process_unionCreate(self, seqid, iprot, oprot):
        args = unionCreate_args()
        args.read(iprot)
        iprot.readMessageEnd()
        result = unionCreate_result()
        try:
            self._handler.unionCreate(args.normal, args.title, args.extra)
            msg_type = TMessageType.REPLY
        except TTransport.TTransportException:
            raise
        except shared.ttypes.NormalException as normalException:
            msg_type = TMessageType.REPLY
            result.normalException = normalException
        except TApplicationException as ex:
            logging.exception('TApplication exception in handler')
            msg_type = TMessageType.EXCEPTION
            result = ex
        except Exception:
            logging.exception('Unexpected exception in handler')
            msg_type = TMessageType.EXCEPTION
            result = TApplicationException(TApplicationException.INTERNAL_ERROR, 'Internal error')
        oprot.writeMessageBegin("unionCreate", msg_type, seqid)
        result.write(oprot)
        oprot.writeMessageEnd()
        oprot.trans.flush()

    def process_unionApply(self, seqid, iprot, oprot):
        args = unionApply_args()
        args.read(iprot)
        iprot.readMessageEnd()
        result = unionApply_result()
        try:
            self._handler.unionApply(args.normal, args.union_id, args.extra)
            msg_type = TMessageType.REPLY
        except TTransport.TTransportException:
            raise
        except shared.ttypes.NormalException as normalException:
            msg_type = TMessageType.REPLY
            result.normalException = normalException
        except TApplicationException as ex:
            logging.exception('TApplication exception in handler')
            msg_type = TMessageType.EXCEPTION
            result = ex
        except Exception:
            logging.exception('Unexpected exception in handler')
            msg_type = TMessageType.EXCEPTION
            result = TApplicationException(TApplicationException.INTERNAL_ERROR, 'Internal error')
        oprot.writeMessageBegin("unionApply", msg_type, seqid)
        result.write(oprot)
        oprot.writeMessageEnd()
        oprot.trans.flush()

# HELPER FUNCTIONS AND STRUCTURES


class unionOfMe_args(object):
    """
    Attributes:
     - normal

    """
    thrift_spec = None


    def __init__(self, normal = None,):
        self.normal = normal

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.STRUCT:
                    self.normal = shared.ttypes.Normal()
                    self.normal.read(iprot)
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        self.validate()
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('unionOfMe_args')
        if self.normal is not None:
            oprot.writeFieldBegin('normal', TType.STRUCT, 1)
            self.normal.write(oprot)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)
all_structs.append(unionOfMe_args)
unionOfMe_args.thrift_spec = (
    None,  # 0
    (1, TType.STRUCT, 'normal', [shared.ttypes.Normal, None], None, ),  # 1
)


class unionOfMe_result(object):
    """
    Attributes:
     - success
     - normalException

    """
    thrift_spec = None


    def __init__(self, success = None, normalException = None,):
        self.success = success
        self.normalException = normalException

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 0:
                if ftype == TType.STRUCT:
                    self.success = UnionOfMe()
                    self.success.read(iprot)
                else:
                    iprot.skip(ftype)
            elif fid == 1:
                if ftype == TType.STRUCT:
                    self.normalException = shared.ttypes.NormalException.read(iprot)
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        self.validate()
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('unionOfMe_result')
        if self.success is not None:
            oprot.writeFieldBegin('success', TType.STRUCT, 0)
            self.success.write(oprot)
            oprot.writeFieldEnd()
        if self.normalException is not None:
            oprot.writeFieldBegin('normalException', TType.STRUCT, 1)
            self.normalException.write(oprot)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)
all_structs.append(unionOfMe_result)
unionOfMe_result.thrift_spec = (
    (0, TType.STRUCT, 'success', [UnionOfMe, None], None, ),  # 0
    (1, TType.STRUCT, 'normalException', [shared.ttypes.NormalException, None], None, ),  # 1
)


class unionList_args(object):
    """
    Attributes:
     - normal
     - page_num
     - page_size

    """
    thrift_spec = None


    def __init__(self, normal = None, page_num = None, page_size = None,):
        self.normal = normal
        self.page_num = page_num
        self.page_size = page_size

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.STRUCT:
                    self.normal = shared.ttypes.Normal()
                    self.normal.read(iprot)
                else:
                    iprot.skip(ftype)
            elif fid == 2:
                if ftype == TType.I32:
                    self.page_num = iprot.readI32()
                else:
                    iprot.skip(ftype)
            elif fid == 3:
                if ftype == TType.I32:
                    self.page_size = iprot.readI32()
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        self.validate()
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('unionList_args')
        if self.normal is not None:
            oprot.writeFieldBegin('normal', TType.STRUCT, 1)
            self.normal.write(oprot)
            oprot.writeFieldEnd()
        if self.page_num is not None:
            oprot.writeFieldBegin('page_num', TType.I32, 2)
            oprot.writeI32(self.page_num)
            oprot.writeFieldEnd()
        if self.page_size is not None:
            oprot.writeFieldBegin('page_size', TType.I32, 3)
            oprot.writeI32(self.page_size)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)
all_structs.append(unionList_args)
unionList_args.thrift_spec = (
    None,  # 0
    (1, TType.STRUCT, 'normal', [shared.ttypes.Normal, None], None, ),  # 1
    (2, TType.I32, 'page_num', None, None, ),  # 2
    (3, TType.I32, 'page_size', None, None, ),  # 3
)


class unionList_result(object):
    """
    Attributes:
     - success
     - normalException

    """
    thrift_spec = None


    def __init__(self, success = None, normalException = None,):
        self.success = success
        self.normalException = normalException

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 0:
                if ftype == TType.STRUCT:
                    self.success = UnionList()
                    self.success.read(iprot)
                else:
                    iprot.skip(ftype)
            elif fid == 1:
                if ftype == TType.STRUCT:
                    self.normalException = shared.ttypes.NormalException.read(iprot)
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        self.validate()
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('unionList_result')
        if self.success is not None:
            oprot.writeFieldBegin('success', TType.STRUCT, 0)
            self.success.write(oprot)
            oprot.writeFieldEnd()
        if self.normalException is not None:
            oprot.writeFieldBegin('normalException', TType.STRUCT, 1)
            self.normalException.write(oprot)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)
all_structs.append(unionList_result)
unionList_result.thrift_spec = (
    (0, TType.STRUCT, 'success', [UnionList, None], None, ),  # 0
    (1, TType.STRUCT, 'normalException', [shared.ttypes.NormalException, None], None, ),  # 1
)


class unionCreate_args(object):
    """
    Attributes:
     - normal
     - title
     - extra

    """
    thrift_spec = None


    def __init__(self, normal = None, title = None, extra = None,):
        self.normal = normal
        self.title = title
        self.extra = extra

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.STRUCT:
                    self.normal = shared.ttypes.Normal()
                    self.normal.read(iprot)
                else:
                    iprot.skip(ftype)
            elif fid == 2:
                if ftype == TType.STRING:
                    self.title = iprot.readString().decode('utf-8', errors='replace') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            elif fid == 3:
                if ftype == TType.STRING:
                    self.extra = iprot.readString().decode('utf-8', errors='replace') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        self.validate()
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('unionCreate_args')
        if self.normal is not None:
            oprot.writeFieldBegin('normal', TType.STRUCT, 1)
            self.normal.write(oprot)
            oprot.writeFieldEnd()
        if self.title is not None:
            oprot.writeFieldBegin('title', TType.STRING, 2)
            oprot.writeString(self.title.encode('utf-8') if sys.version_info[0] == 2 else self.title)
            oprot.writeFieldEnd()
        if self.extra is not None:
            oprot.writeFieldBegin('extra', TType.STRING, 3)
            oprot.writeString(self.extra.encode('utf-8') if sys.version_info[0] == 2 else self.extra)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)
all_structs.append(unionCreate_args)
unionCreate_args.thrift_spec = (
    None,  # 0
    (1, TType.STRUCT, 'normal', [shared.ttypes.Normal, None], None, ),  # 1
    (2, TType.STRING, 'title', 'UTF8', None, ),  # 2
    (3, TType.STRING, 'extra', 'UTF8', None, ),  # 3
)


class unionCreate_result(object):
    """
    Attributes:
     - normalException

    """
    thrift_spec = None


    def __init__(self, normalException = None,):
        self.normalException = normalException

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.STRUCT:
                    self.normalException = shared.ttypes.NormalException.read(iprot)
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        self.validate()
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('unionCreate_result')
        if self.normalException is not None:
            oprot.writeFieldBegin('normalException', TType.STRUCT, 1)
            self.normalException.write(oprot)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)
all_structs.append(unionCreate_result)
unionCreate_result.thrift_spec = (
    None,  # 0
    (1, TType.STRUCT, 'normalException', [shared.ttypes.NormalException, None], None, ),  # 1
)


class unionApply_args(object):
    """
    Attributes:
     - normal
     - union_id
     - extra

    """
    thrift_spec = None


    def __init__(self, normal = None, union_id = None, extra = None,):
        self.normal = normal
        self.union_id = union_id
        self.extra = extra

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.STRUCT:
                    self.normal = shared.ttypes.Normal()
                    self.normal.read(iprot)
                else:
                    iprot.skip(ftype)
            elif fid == 2:
                if ftype == TType.I32:
                    self.union_id = iprot.readI32()
                else:
                    iprot.skip(ftype)
            elif fid == 3:
                if ftype == TType.STRING:
                    self.extra = iprot.readString().decode('utf-8', errors='replace') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        self.validate()
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('unionApply_args')
        if self.normal is not None:
            oprot.writeFieldBegin('normal', TType.STRUCT, 1)
            self.normal.write(oprot)
            oprot.writeFieldEnd()
        if self.union_id is not None:
            oprot.writeFieldBegin('union_id', TType.I32, 2)
            oprot.writeI32(self.union_id)
            oprot.writeFieldEnd()
        if self.extra is not None:
            oprot.writeFieldBegin('extra', TType.STRING, 3)
            oprot.writeString(self.extra.encode('utf-8') if sys.version_info[0] == 2 else self.extra)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)
all_structs.append(unionApply_args)
unionApply_args.thrift_spec = (
    None,  # 0
    (1, TType.STRUCT, 'normal', [shared.ttypes.Normal, None], None, ),  # 1
    (2, TType.I32, 'union_id', None, None, ),  # 2
    (3, TType.STRING, 'extra', 'UTF8', None, ),  # 3
)


class unionApply_result(object):
    """
    Attributes:
     - normalException

    """
    thrift_spec = None


    def __init__(self, normalException = None,):
        self.normalException = normalException

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.STRUCT:
                    self.normalException = shared.ttypes.NormalException.read(iprot)
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        self.validate()
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('unionApply_result')
        if self.normalException is not None:
            oprot.writeFieldBegin('normalException', TType.STRUCT, 1)
            self.normalException.write(oprot)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)
all_structs.append(unionApply_result)
unionApply_result.thrift_spec = (
    None,  # 0
    (1, TType.STRUCT, 'normalException', [shared.ttypes.NormalException, None], None, ),  # 1
)
fix_spec(all_structs)
del all_structs
