#
# Autogenerated by Thrift Compiler (0.22.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py
#

from thrift.Thrift import TType, TMessageType, TFrozenDict, TException, TApplicationException
from thrift.protocol.TProtocol import TProtocolException
from thrift.TRecursive import fix_spec
from uuid import UUID

import sys
import logging
from .ttypes import *
from thrift.Thrift import TProcessor
from thrift.transport import TTransport
all_structs = []


class Iface(object):
    def getVariables(self, normal, idx, ids):
        """
        @description 获取联盟变量值
        @param normal API请求基础信息
        @param idx 联盟索引
        @param ids 变量ID数组
        @returns VariableResponse 变量列表响应
          - Variable: list<VariableInfo> 变量信息列表
        @throws NormalException 获取变量时可能抛出的异常

        Parameters:
         - normal
         - idx
         - ids

        """
        pass

    def doVariable(self, normal, idx, id):
        """
        @description 执行变量操作（可能用于上传分数等）
        @param normal API请求基础信息
        @param idx 联盟索引
        @param id 变量ID
        @returns VariableActionResult 操作结果
          - result: bool 操作是否成功
        @throws NormalException 执行变量操作时可能抛出的异常

        Parameters:
         - normal
         - idx
         - id

        """
        pass

    def batchGetVariables(self, normal, requests):
        """
        @description 批量获取多个联盟变量值
        @param normal API请求基础信息
        @param requests 批量请求列表
        @returns map<string, VariableResponse> 批量响应结果
        @throws NormalException 批量获取变量时可能抛出的异常

        Parameters:
         - normal
         - requests

        """
        pass

    def batchDoVariable(self, normal, requests):
        """
        @description 批量执行变量操作
        @param normal API请求基础信息
        @param requests 批量操作请求列表
        @returns map<string, VariableActionResult> 批量操作结果
        @throws NormalException 批量执行操作时可能抛出的异常

        Parameters:
         - normal
         - requests

        """
        pass


class Client(Iface):
    def __init__(self, iprot, oprot=None):
        self._iprot = self._oprot = iprot
        if oprot is not None:
            self._oprot = oprot
        self._seqid = 0

    def getVariables(self, normal, idx, ids):
        """
        @description 获取联盟变量值
        @param normal API请求基础信息
        @param idx 联盟索引
        @param ids 变量ID数组
        @returns VariableResponse 变量列表响应
          - Variable: list<VariableInfo> 变量信息列表
        @throws NormalException 获取变量时可能抛出的异常

        Parameters:
         - normal
         - idx
         - ids

        """
        self.send_getVariables(normal, idx, ids)
        return self.recv_getVariables()

    def send_getVariables(self, normal, idx, ids):
        self._oprot.writeMessageBegin('getVariables', TMessageType.CALL, self._seqid)
        args = getVariables_args()
        args.normal = normal
        args.idx = idx
        args.ids = ids
        args.write(self._oprot)
        self._oprot.writeMessageEnd()
        self._oprot.trans.flush()

    def recv_getVariables(self):
        iprot = self._iprot
        (fname, mtype, rseqid) = iprot.readMessageBegin()
        if mtype == TMessageType.EXCEPTION:
            x = TApplicationException()
            x.read(iprot)
            iprot.readMessageEnd()
            raise x
        result = getVariables_result()
        result.read(iprot)
        iprot.readMessageEnd()
        if result.success is not None:
            return result.success
        if result.normalException is not None:
            raise result.normalException
        raise TApplicationException(TApplicationException.MISSING_RESULT, "getVariables failed: unknown result")

    def doVariable(self, normal, idx, id):
        """
        @description 执行变量操作（可能用于上传分数等）
        @param normal API请求基础信息
        @param idx 联盟索引
        @param id 变量ID
        @returns VariableActionResult 操作结果
          - result: bool 操作是否成功
        @throws NormalException 执行变量操作时可能抛出的异常

        Parameters:
         - normal
         - idx
         - id

        """
        self.send_doVariable(normal, idx, id)
        return self.recv_doVariable()

    def send_doVariable(self, normal, idx, id):
        self._oprot.writeMessageBegin('doVariable', TMessageType.CALL, self._seqid)
        args = doVariable_args()
        args.normal = normal
        args.idx = idx
        args.id = id
        args.write(self._oprot)
        self._oprot.writeMessageEnd()
        self._oprot.trans.flush()

    def recv_doVariable(self):
        iprot = self._iprot
        (fname, mtype, rseqid) = iprot.readMessageBegin()
        if mtype == TMessageType.EXCEPTION:
            x = TApplicationException()
            x.read(iprot)
            iprot.readMessageEnd()
            raise x
        result = doVariable_result()
        result.read(iprot)
        iprot.readMessageEnd()
        if result.success is not None:
            return result.success
        if result.normalException is not None:
            raise result.normalException
        raise TApplicationException(TApplicationException.MISSING_RESULT, "doVariable failed: unknown result")

    def batchGetVariables(self, normal, requests):
        """
        @description 批量获取多个联盟变量值
        @param normal API请求基础信息
        @param requests 批量请求列表
        @returns map<string, VariableResponse> 批量响应结果
        @throws NormalException 批量获取变量时可能抛出的异常

        Parameters:
         - normal
         - requests

        """
        self.send_batchGetVariables(normal, requests)
        return self.recv_batchGetVariables()

    def send_batchGetVariables(self, normal, requests):
        self._oprot.writeMessageBegin('batchGetVariables', TMessageType.CALL, self._seqid)
        args = batchGetVariables_args()
        args.normal = normal
        args.requests = requests
        args.write(self._oprot)
        self._oprot.writeMessageEnd()
        self._oprot.trans.flush()

    def recv_batchGetVariables(self):
        iprot = self._iprot
        (fname, mtype, rseqid) = iprot.readMessageBegin()
        if mtype == TMessageType.EXCEPTION:
            x = TApplicationException()
            x.read(iprot)
            iprot.readMessageEnd()
            raise x
        result = batchGetVariables_result()
        result.read(iprot)
        iprot.readMessageEnd()
        if result.success is not None:
            return result.success
        if result.normalException is not None:
            raise result.normalException
        raise TApplicationException(TApplicationException.MISSING_RESULT, "batchGetVariables failed: unknown result")

    def batchDoVariable(self, normal, requests):
        """
        @description 批量执行变量操作
        @param normal API请求基础信息
        @param requests 批量操作请求列表
        @returns map<string, VariableActionResult> 批量操作结果
        @throws NormalException 批量执行操作时可能抛出的异常

        Parameters:
         - normal
         - requests

        """
        self.send_batchDoVariable(normal, requests)
        return self.recv_batchDoVariable()

    def send_batchDoVariable(self, normal, requests):
        self._oprot.writeMessageBegin('batchDoVariable', TMessageType.CALL, self._seqid)
        args = batchDoVariable_args()
        args.normal = normal
        args.requests = requests
        args.write(self._oprot)
        self._oprot.writeMessageEnd()
        self._oprot.trans.flush()

    def recv_batchDoVariable(self):
        iprot = self._iprot
        (fname, mtype, rseqid) = iprot.readMessageBegin()
        if mtype == TMessageType.EXCEPTION:
            x = TApplicationException()
            x.read(iprot)
            iprot.readMessageEnd()
            raise x
        result = batchDoVariable_result()
        result.read(iprot)
        iprot.readMessageEnd()
        if result.success is not None:
            return result.success
        if result.normalException is not None:
            raise result.normalException
        raise TApplicationException(TApplicationException.MISSING_RESULT, "batchDoVariable failed: unknown result")


class Processor(Iface, TProcessor):
    def __init__(self, handler):
        self._handler = handler
        self._processMap = {}
        self._processMap["getVariables"] = Processor.process_getVariables
        self._processMap["doVariable"] = Processor.process_doVariable
        self._processMap["batchGetVariables"] = Processor.process_batchGetVariables
        self._processMap["batchDoVariable"] = Processor.process_batchDoVariable
        self._on_message_begin = None

    def on_message_begin(self, func):
        self._on_message_begin = func

    def process(self, iprot, oprot):
        (name, type, seqid) = iprot.readMessageBegin()
        if self._on_message_begin:
            self._on_message_begin(name, type, seqid)
        if name not in self._processMap:
            iprot.skip(TType.STRUCT)
            iprot.readMessageEnd()
            x = TApplicationException(TApplicationException.UNKNOWN_METHOD, 'Unknown function %s' % (name))
            oprot.writeMessageBegin(name, TMessageType.EXCEPTION, seqid)
            x.write(oprot)
            oprot.writeMessageEnd()
            oprot.trans.flush()
            return
        else:
            self._processMap[name](self, seqid, iprot, oprot)
        return True

    def process_getVariables(self, seqid, iprot, oprot):
        args = getVariables_args()
        args.read(iprot)
        iprot.readMessageEnd()
        result = getVariables_result()
        try:
            result.success = self._handler.getVariables(args.normal, args.idx, args.ids)
            msg_type = TMessageType.REPLY
        except TTransport.TTransportException:
            raise
        except shared.ttypes.NormalException as normalException:
            msg_type = TMessageType.REPLY
            result.normalException = normalException
        except TApplicationException as ex:
            logging.exception('TApplication exception in handler')
            msg_type = TMessageType.EXCEPTION
            result = ex
        except Exception:
            logging.exception('Unexpected exception in handler')
            msg_type = TMessageType.EXCEPTION
            result = TApplicationException(TApplicationException.INTERNAL_ERROR, 'Internal error')
        oprot.writeMessageBegin("getVariables", msg_type, seqid)
        result.write(oprot)
        oprot.writeMessageEnd()
        oprot.trans.flush()

    def process_doVariable(self, seqid, iprot, oprot):
        args = doVariable_args()
        args.read(iprot)
        iprot.readMessageEnd()
        result = doVariable_result()
        try:
            result.success = self._handler.doVariable(args.normal, args.idx, args.id)
            msg_type = TMessageType.REPLY
        except TTransport.TTransportException:
            raise
        except shared.ttypes.NormalException as normalException:
            msg_type = TMessageType.REPLY
            result.normalException = normalException
        except TApplicationException as ex:
            logging.exception('TApplication exception in handler')
            msg_type = TMessageType.EXCEPTION
            result = ex
        except Exception:
            logging.exception('Unexpected exception in handler')
            msg_type = TMessageType.EXCEPTION
            result = TApplicationException(TApplicationException.INTERNAL_ERROR, 'Internal error')
        oprot.writeMessageBegin("doVariable", msg_type, seqid)
        result.write(oprot)
        oprot.writeMessageEnd()
        oprot.trans.flush()

    def process_batchGetVariables(self, seqid, iprot, oprot):
        args = batchGetVariables_args()
        args.read(iprot)
        iprot.readMessageEnd()
        result = batchGetVariables_result()
        try:
            result.success = self._handler.batchGetVariables(args.normal, args.requests)
            msg_type = TMessageType.REPLY
        except TTransport.TTransportException:
            raise
        except shared.ttypes.NormalException as normalException:
            msg_type = TMessageType.REPLY
            result.normalException = normalException
        except TApplicationException as ex:
            logging.exception('TApplication exception in handler')
            msg_type = TMessageType.EXCEPTION
            result = ex
        except Exception:
            logging.exception('Unexpected exception in handler')
            msg_type = TMessageType.EXCEPTION
            result = TApplicationException(TApplicationException.INTERNAL_ERROR, 'Internal error')
        oprot.writeMessageBegin("batchGetVariables", msg_type, seqid)
        result.write(oprot)
        oprot.writeMessageEnd()
        oprot.trans.flush()

    def process_batchDoVariable(self, seqid, iprot, oprot):
        args = batchDoVariable_args()
        args.read(iprot)
        iprot.readMessageEnd()
        result = batchDoVariable_result()
        try:
            result.success = self._handler.batchDoVariable(args.normal, args.requests)
            msg_type = TMessageType.REPLY
        except TTransport.TTransportException:
            raise
        except shared.ttypes.NormalException as normalException:
            msg_type = TMessageType.REPLY
            result.normalException = normalException
        except TApplicationException as ex:
            logging.exception('TApplication exception in handler')
            msg_type = TMessageType.EXCEPTION
            result = ex
        except Exception:
            logging.exception('Unexpected exception in handler')
            msg_type = TMessageType.EXCEPTION
            result = TApplicationException(TApplicationException.INTERNAL_ERROR, 'Internal error')
        oprot.writeMessageBegin("batchDoVariable", msg_type, seqid)
        result.write(oprot)
        oprot.writeMessageEnd()
        oprot.trans.flush()

# HELPER FUNCTIONS AND STRUCTURES


class getVariables_args(object):
    """
    Attributes:
     - normal
     - idx
     - ids

    """
    thrift_spec = None


    def __init__(self, normal = None, idx = None, ids = None,):
        self.normal = normal
        self.idx = idx
        self.ids = ids

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.STRUCT:
                    self.normal = shared.ttypes.Normal()
                    self.normal.read(iprot)
                else:
                    iprot.skip(ftype)
            elif fid == 2:
                if ftype == TType.I32:
                    self.idx = iprot.readI32()
                else:
                    iprot.skip(ftype)
            elif fid == 3:
                if ftype == TType.LIST:
                    self.ids = []
                    (_etype17, _size14) = iprot.readListBegin()
                    for _i18 in range(_size14):
                        _elem19 = iprot.readString().decode('utf-8', errors='replace') if sys.version_info[0] == 2 else iprot.readString()
                        self.ids.append(_elem19)
                    iprot.readListEnd()
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        self.validate()
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('getVariables_args')
        if self.normal is not None:
            oprot.writeFieldBegin('normal', TType.STRUCT, 1)
            self.normal.write(oprot)
            oprot.writeFieldEnd()
        if self.idx is not None:
            oprot.writeFieldBegin('idx', TType.I32, 2)
            oprot.writeI32(self.idx)
            oprot.writeFieldEnd()
        if self.ids is not None:
            oprot.writeFieldBegin('ids', TType.LIST, 3)
            oprot.writeListBegin(TType.STRING, len(self.ids))
            for iter20 in self.ids:
                oprot.writeString(iter20.encode('utf-8') if sys.version_info[0] == 2 else iter20)
            oprot.writeListEnd()
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)
all_structs.append(getVariables_args)
getVariables_args.thrift_spec = (
    None,  # 0
    (1, TType.STRUCT, 'normal', [shared.ttypes.Normal, None], None, ),  # 1
    (2, TType.I32, 'idx', None, None, ),  # 2
    (3, TType.LIST, 'ids', (TType.STRING, 'UTF8', False), None, ),  # 3
)


class getVariables_result(object):
    """
    Attributes:
     - success
     - normalException

    """
    thrift_spec = None


    def __init__(self, success = None, normalException = None,):
        self.success = success
        self.normalException = normalException

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 0:
                if ftype == TType.STRUCT:
                    self.success = VariableResponse()
                    self.success.read(iprot)
                else:
                    iprot.skip(ftype)
            elif fid == 1:
                if ftype == TType.STRUCT:
                    self.normalException = shared.ttypes.NormalException.read(iprot)
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        self.validate()
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('getVariables_result')
        if self.success is not None:
            oprot.writeFieldBegin('success', TType.STRUCT, 0)
            self.success.write(oprot)
            oprot.writeFieldEnd()
        if self.normalException is not None:
            oprot.writeFieldBegin('normalException', TType.STRUCT, 1)
            self.normalException.write(oprot)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)
all_structs.append(getVariables_result)
getVariables_result.thrift_spec = (
    (0, TType.STRUCT, 'success', [VariableResponse, None], None, ),  # 0
    (1, TType.STRUCT, 'normalException', [shared.ttypes.NormalException, None], None, ),  # 1
)


class doVariable_args(object):
    """
    Attributes:
     - normal
     - idx
     - id

    """
    thrift_spec = None


    def __init__(self, normal = None, idx = None, id = None,):
        self.normal = normal
        self.idx = idx
        self.id = id

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.STRUCT:
                    self.normal = shared.ttypes.Normal()
                    self.normal.read(iprot)
                else:
                    iprot.skip(ftype)
            elif fid == 2:
                if ftype == TType.I32:
                    self.idx = iprot.readI32()
                else:
                    iprot.skip(ftype)
            elif fid == 3:
                if ftype == TType.I32:
                    self.id = iprot.readI32()
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        self.validate()
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('doVariable_args')
        if self.normal is not None:
            oprot.writeFieldBegin('normal', TType.STRUCT, 1)
            self.normal.write(oprot)
            oprot.writeFieldEnd()
        if self.idx is not None:
            oprot.writeFieldBegin('idx', TType.I32, 2)
            oprot.writeI32(self.idx)
            oprot.writeFieldEnd()
        if self.id is not None:
            oprot.writeFieldBegin('id', TType.I32, 3)
            oprot.writeI32(self.id)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)
all_structs.append(doVariable_args)
doVariable_args.thrift_spec = (
    None,  # 0
    (1, TType.STRUCT, 'normal', [shared.ttypes.Normal, None], None, ),  # 1
    (2, TType.I32, 'idx', None, None, ),  # 2
    (3, TType.I32, 'id', None, None, ),  # 3
)


class doVariable_result(object):
    """
    Attributes:
     - success
     - normalException

    """
    thrift_spec = None


    def __init__(self, success = None, normalException = None,):
        self.success = success
        self.normalException = normalException

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 0:
                if ftype == TType.STRUCT:
                    self.success = VariableActionResult()
                    self.success.read(iprot)
                else:
                    iprot.skip(ftype)
            elif fid == 1:
                if ftype == TType.STRUCT:
                    self.normalException = shared.ttypes.NormalException.read(iprot)
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        self.validate()
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('doVariable_result')
        if self.success is not None:
            oprot.writeFieldBegin('success', TType.STRUCT, 0)
            self.success.write(oprot)
            oprot.writeFieldEnd()
        if self.normalException is not None:
            oprot.writeFieldBegin('normalException', TType.STRUCT, 1)
            self.normalException.write(oprot)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)
all_structs.append(doVariable_result)
doVariable_result.thrift_spec = (
    (0, TType.STRUCT, 'success', [VariableActionResult, None], None, ),  # 0
    (1, TType.STRUCT, 'normalException', [shared.ttypes.NormalException, None], None, ),  # 1
)


class batchGetVariables_args(object):
    """
    Attributes:
     - normal
     - requests

    """
    thrift_spec = None


    def __init__(self, normal = None, requests = None,):
        self.normal = normal
        self.requests = requests

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.STRUCT:
                    self.normal = shared.ttypes.Normal()
                    self.normal.read(iprot)
                else:
                    iprot.skip(ftype)
            elif fid == 2:
                if ftype == TType.LIST:
                    self.requests = []
                    (_etype24, _size21) = iprot.readListBegin()
                    for _i25 in range(_size21):
                        _elem26 = VariableBatchRequest()
                        _elem26.read(iprot)
                        self.requests.append(_elem26)
                    iprot.readListEnd()
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        self.validate()
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('batchGetVariables_args')
        if self.normal is not None:
            oprot.writeFieldBegin('normal', TType.STRUCT, 1)
            self.normal.write(oprot)
            oprot.writeFieldEnd()
        if self.requests is not None:
            oprot.writeFieldBegin('requests', TType.LIST, 2)
            oprot.writeListBegin(TType.STRUCT, len(self.requests))
            for iter27 in self.requests:
                iter27.write(oprot)
            oprot.writeListEnd()
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)
all_structs.append(batchGetVariables_args)
batchGetVariables_args.thrift_spec = (
    None,  # 0
    (1, TType.STRUCT, 'normal', [shared.ttypes.Normal, None], None, ),  # 1
    (2, TType.LIST, 'requests', (TType.STRUCT, [VariableBatchRequest, None], False), None, ),  # 2
)


class batchGetVariables_result(object):
    """
    Attributes:
     - success
     - normalException

    """
    thrift_spec = None


    def __init__(self, success = None, normalException = None,):
        self.success = success
        self.normalException = normalException

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 0:
                if ftype == TType.MAP:
                    self.success = {}
                    (_ktype29, _vtype30, _size28) = iprot.readMapBegin()
                    for _i32 in range(_size28):
                        _key33 = iprot.readString().decode('utf-8', errors='replace') if sys.version_info[0] == 2 else iprot.readString()
                        _val34 = VariableResponse()
                        _val34.read(iprot)
                        self.success[_key33] = _val34
                    iprot.readMapEnd()
                else:
                    iprot.skip(ftype)
            elif fid == 1:
                if ftype == TType.STRUCT:
                    self.normalException = shared.ttypes.NormalException.read(iprot)
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        self.validate()
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('batchGetVariables_result')
        if self.success is not None:
            oprot.writeFieldBegin('success', TType.MAP, 0)
            oprot.writeMapBegin(TType.STRING, TType.STRUCT, len(self.success))
            for kiter35, viter36 in self.success.items():
                oprot.writeString(kiter35.encode('utf-8') if sys.version_info[0] == 2 else kiter35)
                viter36.write(oprot)
            oprot.writeMapEnd()
            oprot.writeFieldEnd()
        if self.normalException is not None:
            oprot.writeFieldBegin('normalException', TType.STRUCT, 1)
            self.normalException.write(oprot)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)
all_structs.append(batchGetVariables_result)
batchGetVariables_result.thrift_spec = (
    (0, TType.MAP, 'success', (TType.STRING, 'UTF8', TType.STRUCT, [VariableResponse, None], False), None, ),  # 0
    (1, TType.STRUCT, 'normalException', [shared.ttypes.NormalException, None], None, ),  # 1
)


class batchDoVariable_args(object):
    """
    Attributes:
     - normal
     - requests

    """
    thrift_spec = None


    def __init__(self, normal = None, requests = None,):
        self.normal = normal
        self.requests = requests

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.STRUCT:
                    self.normal = shared.ttypes.Normal()
                    self.normal.read(iprot)
                else:
                    iprot.skip(ftype)
            elif fid == 2:
                if ftype == TType.LIST:
                    self.requests = []
                    (_etype40, _size37) = iprot.readListBegin()
                    for _i41 in range(_size37):
                        _elem42 = VariableBatchRequest()
                        _elem42.read(iprot)
                        self.requests.append(_elem42)
                    iprot.readListEnd()
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        self.validate()
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('batchDoVariable_args')
        if self.normal is not None:
            oprot.writeFieldBegin('normal', TType.STRUCT, 1)
            self.normal.write(oprot)
            oprot.writeFieldEnd()
        if self.requests is not None:
            oprot.writeFieldBegin('requests', TType.LIST, 2)
            oprot.writeListBegin(TType.STRUCT, len(self.requests))
            for iter43 in self.requests:
                iter43.write(oprot)
            oprot.writeListEnd()
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)
all_structs.append(batchDoVariable_args)
batchDoVariable_args.thrift_spec = (
    None,  # 0
    (1, TType.STRUCT, 'normal', [shared.ttypes.Normal, None], None, ),  # 1
    (2, TType.LIST, 'requests', (TType.STRUCT, [VariableBatchRequest, None], False), None, ),  # 2
)


class batchDoVariable_result(object):
    """
    Attributes:
     - success
     - normalException

    """
    thrift_spec = None


    def __init__(self, success = None, normalException = None,):
        self.success = success
        self.normalException = normalException

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 0:
                if ftype == TType.MAP:
                    self.success = {}
                    (_ktype45, _vtype46, _size44) = iprot.readMapBegin()
                    for _i48 in range(_size44):
                        _key49 = iprot.readString().decode('utf-8', errors='replace') if sys.version_info[0] == 2 else iprot.readString()
                        _val50 = VariableActionResult()
                        _val50.read(iprot)
                        self.success[_key49] = _val50
                    iprot.readMapEnd()
                else:
                    iprot.skip(ftype)
            elif fid == 1:
                if ftype == TType.STRUCT:
                    self.normalException = shared.ttypes.NormalException.read(iprot)
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        self.validate()
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('batchDoVariable_result')
        if self.success is not None:
            oprot.writeFieldBegin('success', TType.MAP, 0)
            oprot.writeMapBegin(TType.STRING, TType.STRUCT, len(self.success))
            for kiter51, viter52 in self.success.items():
                oprot.writeString(kiter51.encode('utf-8') if sys.version_info[0] == 2 else kiter51)
                viter52.write(oprot)
            oprot.writeMapEnd()
            oprot.writeFieldEnd()
        if self.normalException is not None:
            oprot.writeFieldBegin('normalException', TType.STRUCT, 1)
            self.normalException.write(oprot)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)
all_structs.append(batchDoVariable_result)
batchDoVariable_result.thrift_spec = (
    (0, TType.MAP, 'success', (TType.STRING, 'UTF8', TType.STRUCT, [VariableActionResult, None], False), None, ),  # 0
    (1, TType.STRUCT, 'normalException', [shared.ttypes.NormalException, None], None, ),  # 1
)
fix_spec(all_structs)
del all_structs
